import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const LanguageContext = createContext(null);

const COPY = {
  en: {
    greetingMorning: 'Good morning',
    greetingAfternoon: 'Good afternoon',
    greetingEvening: 'Good evening',
    greetingFallback: 'there',
    dateLocale: 'en-US',
    activeCourses: 'Active Courses',
    dayStreak: 'Day Streak',
    aiInteractions: 'AI Interactions',
    yourCourses: 'Your Courses',
    syncClassroom: 'Sync Classroom',
    syncing: 'Syncing...',
    noCoursesTitle: 'No courses found',
    noCoursesBody: 'Your dashboard is empty. Click "Sync Classroom" to fetch your official courses from Google.',
    quickActions: 'Quick Actions',
    askAi: 'Ask AI',
    askAiDesc: 'Instant help from your teaching assistant',
    summarize: 'Summarize',
    summarizeDesc: 'Condense lecture notes instantly',
    takeQuiz: 'Take a Quiz',
    takeQuizDesc: 'Test knowledge with AI quizzes',
    gradeEssay: 'Grade Essay',
    gradeEssayDesc: 'Predict your IELTS band score',
    lightMode: 'Light',
    darkMode: 'Dark',
    language: 'Language',
    navHome: 'Home',
    navCourses: 'Courses',
    navAiAgents: 'AI Agents',
    navFocusBreak: 'Focus & Break',
    navPomodoro: 'Pomodoro',
    navMiniGames: 'Mini Games',
    navSupport: 'Support',
    navUserManual: 'User Manual',
    navProfile: 'Profile',
    signOut: 'Sign out',
    availableDuringBreak: 'Available during break',
    backToAiAgents: 'Back to AI Agents',
    myCourses: 'My Courses',
    searchCourses: 'Search courses...',
    noCoursesMatch: 'No courses found matching your search.',
    noCourseSelected: 'No Course Selected',
    noCourseSelectedBody: 'Select a course from the sidebar to view its official documents, assignments, and lecture materials.',
    courseMaterials: 'Course Materials',
    files: 'Files',
    folderEmpty: 'Folder is Empty',
    folderEmptyBody: 'No documents have been synced from Google Classroom for this course yet.',
    coursesLoadError: 'Failed to load courses. Please try again.',
    downloadError: 'Failed to download document.',
    previewError: 'Failed to load document preview.',
    backToDashboard: 'Back to Dashboard',
    signInTagline: 'Your personalized AI-powered learning companion to enhance your educational journey.',
    signInButton: 'Continue with Google',
    aiAgentLabel: 'AI Agent',
    aiAgentsSubtitle: 'Choose an agent to get started',
    aiAgentsHint: 'Select an agent to begin • Hover to preview',
    aiSummarizerTitle: 'Summarizer',
    aiSummarizerContent: 'Turn long lecture notes into concise, exam-ready summaries.',
    aiQuizTitle: 'Quiz Generator',
    aiQuizContent: 'Generate practice quizzes from text or course documents.',
    aiChatTitle: 'AI Tutor Chat',
    aiChatContent: 'Ask follow-up questions and get concept explanations instantly.',
    aiEvaluatorTitle: 'Evaluator',
    aiEvaluatorContent: 'Evaluate summary quality and get structured feedback.',
    aiEssayTitle: 'Essay Grader',
    aiEssayContent: 'Predict IELTS band score and receive writing guidance.',
    profileKicker: 'Study Profile',
    profileTitleFallback: 'Student',
    profileSubtitle: 'Your learning hub and progress snapshot.',
    profileTotalInteractions: 'Total interactions',
    profileStreakBonus: 'Streak bonus',
    profileXp: 'Experience',
    profileLevel: 'Level',
    profileNextLevel: 'Next level at',
    profileRankFallback: 'Unranked',
    profileActiveCourses: 'Active Courses',
    profileStreak: 'Day Streak',
    profileFocusHours: 'Focus Hours',
    profileCompletedCycles: 'Focus Cycles',
    profileAchievements: 'Achievements',
    profileAchievementsHint: 'Progress updates daily',
    profileAchieved: 'Achieved',
    profileDailyTasks: 'Daily Tasks',
    profileTaskEmpty: 'No tasks yet. Complete a few actions to unlock today’s goals.',
    profileLoadingTasks: 'Updating tasks...',
    profileTaskCompleted: 'Completed',
    profileTaskReward: 'Reward',
    profileLearningProfile: 'Learning Profile',
    profileLoadingCourses: 'Loading courses...',
    profileNoCourses: 'No courses yet. Sync or create one to begin.',
    profileNextAction: 'Next action',
    profileOpenCourse: 'Open course',
    profileSettings: 'Account Settings',
    profileTheme: 'Theme',
    profileThemeDark: 'Dark',
    profileThemeLight: 'Light',
    profileLanguage: 'Language',
    profileNotifications: 'Notifications',
    automationTitle: 'Automation Preferences',
    automationBody: 'Choose the courses that should run automation.',
    automationAllCourses: 'All courses',
    automationEmpty: 'No courses available yet. Sync or create a course first.',
    automationSelectionHint: 'Select at least one course or choose "All courses".',
    automationSave: 'Save automation settings',
    automationSaved: 'Saved',
    automationModalTitle: 'Choose courses for automation',
    automationModalBody: 'Select which courses should be automated. You can change this later in Profile settings.',
    automationModalCta: 'Save and continue',
    profileAchievementStreak: '3-day streak',
    profileAchievementStreak7: '7-day streak',
    profileAchievementStreak14: '14-day streak',
    profileAchievementSummaries: '3 summaries created',
    profileAchievementSummaries10: '10 summaries created',
    profileAchievementQuizzes: '2 quizzes generated',
    profileAchievementQuizzes10: '10 quizzes generated',
    profileAchievementFocus: '3 focus cycles',
    profileAchievementFocus10: '10 focus cycles',
    profileAchievementChats20: '20 tutor chats',
    profileAchievementEssays5: '5 essays graded',
    profileAchievementEvaluations5: '5 evaluations completed',
    profileTaskDailySummariesTitle: 'Summarize twice',
    profileTaskDailySummariesDesc: 'Generate 2 summaries today',
    profileTaskDailyQuizTitle: 'Quiz accuracy',
    profileTaskDailyQuizDesc: 'Answer 5 quiz questions correctly',
    profileTaskDailyFocusTitle: 'Focus sessions',
    profileTaskDailyFocusDesc: 'Complete 2 pomodoro cycles',
    profileTaskDailyTutorTitle: 'Ask the tutor',
    profileTaskDailyTutorDesc: 'Send 3 tutor questions',
    profileTaskDailyEssayTitle: 'Grade an essay',
    profileTaskDailyEssayDesc: 'Submit 1 essay for grading',
    profileTaskDailyEvaluationTitle: 'Evaluate a summary',
    profileTaskDailyEvaluationDesc: 'Run 1 summary evaluation',
    profileLeaderboard: 'Leaderboard',
    profileLeaderboardEmpty: 'No leaderboard data yet.',
    profileNextSummary: 'Create your first summary',
    profileNextQuiz: 'Generate a quiz',
    profileNextFocus: 'Start a focus session',
    profileNextReview: 'Review a recent result',
    timelineComplete: 'COMPLETE',
    timelineInProgress: 'IN PROGRESS',
    timelinePending: 'PENDING',
    timelineEnergy: 'Energy Level',
    timelineConnected: 'Connected Nodes',
    chatSeed: 'What are we learning today?',
    chatHeader: 'How can I assist you?',
    chatGeneral: 'General Chat',
    chatCourseContext: 'Course Context',
    chatSelectCourse: 'Select Course...',
    chatSelectDocument: 'Select Document...',
    chatAskPlaceholder: 'Ask a question...',
    chatError: '⚠️ Error connecting to chatbot. Please select a course if using Context Mode.',
    chatHistoryTab: 'History',
    chatHistoryTitle: 'Conversation History',
    chatHistoryNew: 'New chat',
    chatHistoryGeneralLabel: 'General',
    chatHistoryCourseLabel: 'Course',
    chatHistoryEmpty: 'No conversations yet.',
    chatHistorySelectCourse: 'Select a course to see history.',
    chatHistoryAuth: 'Log in to see your history.',
    chatHistoryLoading: 'Loading history...',
    chatHistoryLoadError: 'Unable to load history. Try again.',
    chatHistoryPreviewEmpty: 'No messages yet',
    chatTabChat: 'Chat',
    chatSpeak: 'Play answer audio',
    chatMicStart: 'Start recording',
    chatMicStop: 'Stop recording',
    chatMicUnsupported: 'Microphone access is not supported in this browser.',
    chatMicError: 'Microphone or transcription failed. Please try again.',
    chatMicEmpty: 'No speech detected. Try again.',
    chatTranscribing: 'Transcribing audio…',
    chatTtsError: 'Audio playback failed. Please try again.',
    quizTitle: 'AI Quiz Engine',
    quizSubtitle: 'Generate tests from your materials, or practice past quizzes.',
    quizTabGenerate: 'Generate Quiz',
    quizTabTake: 'Take a Quiz',
    quizSettings: 'Quiz Settings',
    quizSourceDocument: 'Document',
    quizSourceUpload: 'Upload',
    quizSourceText: 'Text',
    quizCourseLabel: 'Course Link',
    quizLoadingCourses: 'Loading courses…',
    quizSelectDocument: 'Select Document',
    quizLoading: 'Loading...',
    quizNoDocs: 'No docs found',
    quizChooseDocument: 'Choose a document...',
    quizUploadBrowse: 'Click to browse PDF',
    quizPasteTextLabel: 'Paste Text',
    quizPasteTextPlaceholder: 'Paste lecture notes here...',
    quizQuestionsLabel: 'Questions',
    quizOptionsLabel: 'Options',
    quizGenerating: 'Generating...',
    quizBuild: 'Build Quiz',
    quizSaved: 'Quiz saved! Find it in the "Take a Quiz" tab.',
    quizEphemeral: 'Ephemeral Quiz generated! (Not saved to database).',
    quizEmptyState: 'Configure settings and generate a quiz to start practicing.',
    quizYourQuizzes: 'Your Quizzes',
    quizLoadingQuizzes: 'Loading quizzes...',
    quizNoQuizzes: 'No quizzes for this course yet.',
    quizLabel: 'Quiz',
    quizTakeQuiz: 'Take Quiz',
    quizBackToQuizzes: 'Back to Quizzes',
    quizRevealAnswers: 'Reveal Score',
    quizReset: 'Reset',
    quizScoreLabel: 'Score',
    quizAnswerLabel: 'Answer',
    quizDataNotFound: 'Data not found',
    quizGenerationFailed: 'Quiz generation failed.',
    summarizerTitle: 'AI Summarizer',
    summarizerSubtitle: 'Transform lengthy lecture materials or uploaded PDFs into concise notes.',
    summarizerConfig: 'Configuration',
    summarizerSourceDocument: 'Course Document',
    summarizerSourceUpload: 'Upload PDF',
    summarizerSelectCourse: 'Select Course',
    summarizerChooseCourse: 'Choose a course...',
    summarizerSelectDocument: 'Select Document',
    summarizerSelectCourseFirst: 'Select course first',
    summarizerNoDocs: 'No documents found',
    summarizerChooseDocument: 'Choose a document...',
    summarizerClickBrowse: 'Click to browse PDF',
    summarizerProcessedMemory: 'Processed in memory, never saved.',
    summarizerProcessing: 'Processing AI...',
    summarizerGenerate: 'Generate Summary',
    summarizerOutput: 'Summary Output',
    summarizerEmpty: 'Select a source and click generate to view the AI summary here.',
    summarizerError: 'Failed to generate summary. Please check your backend connection.',
    summarizerTabGenerate: 'Generate Summary',
    summarizerTabLibrary: 'My Summaries',
    summarizerLibraryTitle: 'Summary Library',
    summarizerLibrarySelectCourse: 'Filter by Course',
    summarizerLibraryAllCourses: 'All courses',
    summarizerLibraryLoading: 'Loading summaries...',
    summarizerLibraryEmpty: 'No summaries yet.',
    summarizerLibrarySelectHint: 'Select a summary to view it.',
    summarizerLibraryRefresh: 'Refresh',
    summarizerLibraryError: 'Failed to load summaries.',
    syncNewDocTitle: 'New document synced',
    syncSummaryQueuedTitle: 'Summary is getting ready',
    syncSummaryQueuedContent: 'Your summary is being prepared in the background.',
    syncSummaryReadyTitle: 'Summary is ready',
    syncSummaryReadyContent: 'Your summary is ready to open.',
    syncSummaryQueuedGeneric: 'We are preparing your new summaries.',
    syncQuizQueuedTitle: 'Quiz is getting ready',
    syncQuizQueuedContent: 'Your quiz is being prepared in the background.',
    syncQuizReadyTitle: 'Quiz is ready',
    syncQuizReadyContent: 'Your quiz is ready to take.',
    syncQuizQueuedGeneric: 'We are preparing your new quizzes.',
    docTypeAnnouncement: 'Announcement',
    docTypePost: 'Post',
    docTypeMaterial: 'Material',
    docTypeCoursework: 'Coursework',
    docTypeUpload: 'Uploaded File',
    docTypeDocument: 'Document',
    docNoContent: 'No content available.',
    evaluatorCourseLabel: 'Course',
    evaluatorLoadingCourses: 'Loading courses…',
    evaluatorLectureTitle: 'Lecture / Source Material',
    evaluatorInputType: 'Input type',
    evaluatorInputText: 'Enter Text',
    evaluatorInputDocument: 'Course Document',
    evaluatorLecturePlaceholder: 'Paste the original lecture notes or source material…',
    evaluatorChars: 'chars',
    evaluatorSelectDocument: 'Select document',
    evaluatorLoadingDocuments: 'Loading documents…',
    evaluatorNoUsableDocs: 'No usable documents found for this course. Sync Google Classroom materials first, or paste text manually.',
    evaluatorStudentSummaryTitle: 'Student Summary',
    evaluatorStudentSummaryPlaceholder: "Paste the student's summary to evaluate…",
    evaluatorSummaryInputType: 'Summary input type',
    evaluatorSummaryInputText: 'Enter Text',
    evaluatorSummaryInputUpload: 'Upload PDF',
    evaluatorSummaryUploadBrowse: 'Click to browse PDF',
    evaluatorSummaryUploadHint: 'Upload the student summary as a PDF file.',
    evaluatorStudentWordsUpload: 'PDF upload',
    evaluatorEvaluating: 'Evaluating…',
    evaluatorEvaluate: 'Evaluate Summary',
    evaluatorFailed: 'Evaluation failed.',
    evaluatorOverallScore: 'Overall Score',
    evaluatorStudentWords: 'Student words',
    evaluatorReferenceWords: 'Reference words',
    evaluatorKeyPoints: 'Key points',
    evaluatorMetrics: 'Metrics',
    evaluatorMetric: 'Metric',
    evaluatorScore: 'Score',
    evaluatorVisual: 'Visual',
    evaluatorDetails: 'Details / AI Feedback',
    evaluatorShowTechnical: 'Show technical details',
    evaluatorHideTechnical: 'Hide technical details',
    metricStrengthStrong: 'Strong.',
    metricStrengthOkay: 'Fair.',
    metricStrengthWeak: 'Needs work.',
    metricEvalError: 'We could not score this reliably. Try again or shorten the lecture.',
    metricCorrectness: 'Correctness',
    metricCorrectnessDesc: 'How close the summary is to the lecture and a reference summary.',
    metricRelevance: 'Relevance',
    metricRelevanceDesc: 'How well the summary focuses on the main lecture topics.',
    metricCoherence: 'Coherence',
    metricCoherenceDesc: 'How clear and well-organized the summary is.',
    metricCompleteness: 'Completeness',
    metricCompletenessDesc: 'How many important lecture points are included.',
    metricConciseness: 'Conciseness',
    metricConcisenessDesc: 'How close the length is to the reference summary.',
    metricTerminology: 'Terminology',
    metricTerminologyDesc: 'Use of important lecture terms.',
    metricHallucination: 'Hallucination',
    metricHallucinationDesc: 'Checks for claims not supported by the lecture.',
    metricMissingKeyPoints: 'Missing Key Points',
    metricMissingKeyPointsDesc: 'Important points from the lecture that were not mentioned.',
    metricFactualAccuracy: 'Factual Accuracy',
    metricFactualAccuracyDesc: 'Whether specific details and facts are correct.',
    metricCriticalAnalysis: 'Critical Analysis',
    metricCriticalAnalysisDesc: 'Depth of reasoning and connections between ideas.',
    essayPromptTitle: 'Essay Prompt (Optional)',
    essayPromptPlaceholder: 'Paste the essay question/prompt if your model was trained with question context...',
    essayInputType: 'Essay input type',
    essayInputText: 'Enter Text',
    essayInputUpload: 'Upload PDF',
    essayStudentEssay: 'Student Essay',
    essayTextPlaceholder: 'Paste the full essay text to predict IELTS band...',
    essayUploadBrowse: 'Click to browse PDF',
    essayUploadHint: 'Upload the student essay as a PDF file.',
    essayGrading: 'Grading...',
    essayPredict: 'Predict IELTS Band',
    essayEnterTextHint: 'Enter text in Student Essay to enable grading.',
    essayPredictedBand: 'Predicted IELTS Band',
    essayObjective: 'Objective',
    essayFailed: 'Essay grading failed.',
    pomodoroKicker: 'Productivity Focus',
    pomodoroBreak: 'Break Time',
    pomodoroFocus: 'Focus Session',
    pomodoroStart: 'Start',
    pomodoroPause: 'Pause',
    pomodoroReset: 'Reset',
    pomodoroSkipBreak: 'Skip Break',
    pomodoroModeWork: 'WORK',
    pomodoroModeBreak: 'BREAK',
    pomodoroAutoStart: 'Auto-start next session',
    pomodoroSessionSettings: 'Session Settings',
    pomodoroWorkSession: 'Work Session',
    pomodoroShortBreak: 'Short Break',
    pomodoroMinutes: 'minutes',
    pomodoroProgressBonus: 'Progress Bonus',
    pomodoroCompletedCycles: 'Completed Cycles',
    pomodoroStreakBonus: 'Streak Bonus',
    pomodoroNote: 'Every full focus cycle adds +10 streak points.',
    miniLockedTitle: 'Mini Games Locked',
    miniLockedBody: 'This tab is only available during Pomodoro breaks.',
    miniMemoryMatch: 'Memory Match',
    miniReset: 'Reset',
    miniMoves: 'Moves',
    miniCompleted: 'Completed!',
    miniPuzzle: '8-Puzzle',
    miniSolved: 'Solved!',
    miniPlay: 'Play',
    miniBackToGames: 'Back to Games',
    miniBreakMode: 'Break Mode Active',
    miniRelax: 'Relax with mini games',
    miniBreakEnds: 'Break ends in',
    miniUnavailable: 'Temporarily unavailable.',
    miniSlideTiles: 'Slide tiles into order from 1 to 8.',
    miniReactionClicker: 'Reaction Clicker',
    miniComingSoon: 'To be added soon',
    miniEmptyTile: 'Empty tile',
    miniTile: 'Tile',
    focusHubTitle: 'Focus Hub',
    tabFocusTimer: 'Focus Timer',
    tabMiniGames: 'Mini Games',
    dailyGoal: 'Daily Goal',
    todayFocus: 'Today',
    sessionTimeline: 'Session Timeline',
    focusGoalLabel: 'Goal',
    noSessionsYet: 'No sessions yet today',
    keyboardHintSpace: 'Space to start/pause',
    keyboardHintR: 'R to reset',
    gamesLockedHint: 'Complete a focus session to unlock games during your break',
    minutesShort: 'min',
    hoursShort: 'h',
    focusQuote1: 'The secret of getting ahead is getting started.',
    focusQuote2: 'Focus on being productive instead of busy.',
    focusQuote3: 'Small daily improvements lead to stunning results.',
    focusQuote4: 'Your focus determines your reality.',
    focusQuote5: 'Deep work is the superpower of the 21st century.',
    focusQuote6: 'Discipline is choosing what you want most over what you want now.',
    miniMemoryDesc: 'Match pairs of cards to test your memory.',
    miniMemoryCardAlt: 'Memory card',
    miniGamesPageTitle: 'Mini Games',
    miniGamesPageSubtitle: 'Take a brain break with fun mini games',
    miniBackToTimer: 'Back to Focus Timer',
    miniGoToGames: 'Play Mini Games',
    miniBreakCta: "You've earned a break! Relax with a quick game.",
    miniStartFocusFirst: 'Start a focus session to unlock games',
    reactionTitle: 'Reaction Clicker',
    reactionDesc: 'Test your reflexes! Click as fast as you can.',
    reactionWait: 'Wait for green...',
    reactionGo: 'CLICK NOW!',
    reactionTooEarly: 'Too early! Click to try again',
    reactionResult: 'Your reaction time',
    reactionMs: 'ms',
    reactionBest: 'Best',
    reactionAverage: 'Average',
    reactionRound: 'Round',
    reactionPlayAgain: 'Play Again',
    reactionRatingLightning: 'Lightning fast!',
    reactionRatingFast: 'Fast reflexes!',
    reactionRatingGood: 'Good reaction!',
    reactionRatingSlow: 'Keep practicing!',
    manualKicker: 'Platform Guide',
    manualTitle: 'MultiAgent AI Teaching Assistant User Manual',
    manualLead: 'This website is built to help students study faster and smarter by combining multiple AI tools in one workflow. Its main purpose is to support learning from classroom materials through summarization, quiz practice, tutoring conversations, and writing evaluation.',
    manualPurposeTitle: 'Primary Purpose Of The Website',
    manualPurposeList1: 'Centralize course content and AI learning tools in a single platform.',
    manualPurposeList2: 'Transform raw study material into summaries, quizzes, and guided explanations.',
    manualPurposeList3: 'Improve comprehension, retention, and writing performance with practical feedback loops.',
    manualPurposeList4: 'Reduce study time while increasing confidence before assessments.',
    manualUserManualTitle: 'User Manual (Current Tab)',
    manualUserManualHeading: 'User Manual',
    manualUserManualPurpose: 'This page is the central reference for using the platform and understanding how each feature fits your study workflow.',
    manualUserManualDescription: 'It explains the website purpose, the function of every left-side tab, and a recommended way to move from setup to revision. You can also share it with first-time users as a quick onboarding guide.',
    manualLeftTabsTitle: 'What Each Left-Side Tab Does',
    manualTabDashboard: 'Dashboard',
    manualTabDashboardPurpose: 'Your home overview after sign-in.',
    manualTabDashboardDetail1: 'Shows your greeting, date, and key study stats in one place.',
    manualTabDashboardDetail2: 'Lets you sync Google Classroom and refresh your enrolled course list.',
    manualTabDashboardDetail3: 'Provides quick action cards to open Chat, Summarizer, Quiz, and Essay Grader faster.',
    manualTabCourses: 'Courses',
    manualTabCoursesPurpose: 'Manage courses and their study materials.',
    manualTabCoursesDetail1: 'Open a course to view synced Google Classroom materials.',
    manualTabCoursesDetail2: 'Preview Drive documents in a new tab when needed.',
    manualTabPomodoro: 'Pomodoro',
    manualTabPomodoroPurpose: 'Run focused study sessions with timed breaks.',
    manualTabPomodoroDetail1: 'Default cycle is 30 minutes work + 5 minutes break, with editable durations.',
    manualTabPomodoroDetail2: 'Includes Start, Pause, Reset, Skip Break, and optional auto-start next session.',
    manualTabPomodoroDetail3: 'Tracks completed cycles and streak bonus points during your study routine.',
    manualTabMiniGames: 'Mini Games',
    manualTabMiniGamesPurpose: 'Take short break-time game sessions to refresh focus.',
    manualTabMiniGamesDetail1: 'Locked during work mode and unlocks only while Pomodoro break mode is active.',
    manualTabMiniGamesDetail2: 'Currently includes Memory Match with image cards and full-screen play mode.',
    manualTabMiniGamesDetail3: 'Returns you to study flow when break ends and game access is locked again.',
    manualTabSummarizer: 'Summarizer',
    manualTabSummarizerPurpose: 'Turn long content into concise study notes.',
    manualTabSummarizerDetail1: 'Paste text or select course documents to generate focused summaries.',
    manualTabSummarizerDetail2: 'Saves time before revision by extracting key concepts quickly.',
    manualTabSummarizerDetail3: 'Useful before exams to create rapid review material.',
    manualTabQuiz: 'Quiz Generator',
    manualTabQuizPurpose: 'Create and take AI-generated quizzes.',
    manualTabQuizDetail1: 'Generate quiz questions from custom text or course materials.',
    manualTabQuizDetail2: 'Adjust number of questions and options to match your level.',
    manualTabQuizDetail3: 'Switch to Take a Quiz mode to practice with saved quizzes by course.',
    manualTabChat: 'AI Tutor Chat',
    manualTabChatPurpose: 'Ask questions and get guided explanations.',
    manualTabChatDetail1: 'Use conversational learning to clarify topics step-by-step.',
    manualTabChatDetail2: 'Great for follow-up questions when lecture notes are confusing.',
    manualTabChatDetail3: 'Supports quick concept checks while you study.',
    manualTabEvaluator: 'Evaluator',
    manualTabEvaluatorPurpose: 'Evaluate summary quality and coverage.',
    manualTabEvaluatorDetail1: 'Compare generated summaries against expected quality dimensions.',
    manualTabEvaluatorDetail2: 'Highlights strengths and weak points to improve summary writing.',
    manualTabEvaluatorDetail3: 'Helps verify whether your notes preserved the essential meaning.',
    manualTabEssay: 'Essay Grader',
    manualTabEssayPurpose: 'Estimate essay quality using the grading model.',
    manualTabEssayDetail1: 'Submit essay text and receive an AI-based score with feedback cues.',
    manualTabEssayDetail2: 'Useful for iterative writing practice before final submissions.',
    manualTabEssayDetail3: 'Supports self-assessment and faster writing improvement cycles.',
    userManualHeroKicker: 'Documentation',
    userManualHeroTitle: 'User Manual',
    userManualHeroLead: 'Everything you need to know about Squee Learn - from syncing your Google Classroom to getting the most out of each AI tool.',
    userManualOverviewTitle: 'Platform Overview',
    userManualOverviewSubtitle: 'What Squee Learn is and how it helps you',
    userManualOverviewBody: 'is a multi-agent AI teaching assistant designed to help students study smarter. It connects directly to your Google Classroom to sync your courses and documents automatically, then provides a suite of AI-powered tools that work on your actual course material - no manual copy-pasting required.',
    userManualOverviewHighlightAgentsLabel: '5 AI agents',
    userManualOverviewHighlightAgentsBody: 'summariser, quiz generator, chat tutor, evaluator, essay grader',
    userManualOverviewHighlightSyncLabel: 'Auto-sync',
    userManualOverviewHighlightSyncBody: 'your Google Classroom courses and PDFs sync on every login',
    userManualOverviewHighlightFocusLabel: 'Focus tools',
    userManualOverviewHighlightFocusBody: 'a Pomodoro timer that unlocks mini-games during breaks',
    userManualOverviewHighlightProgressLabel: 'Progress tracking',
    userManualOverviewHighlightProgressBody: 'day streak, AI interaction count, and per-session stats',
    userManualOverviewTipLabel: 'Two account types:',
    userManualOverviewTipBody: 'Sign in with Google to get Classroom sync, or create a local account and upload PDFs manually in any AI tool. Both types have full access to all AI features.',
    userManualDashboardTitle: 'Dashboard',
    userManualDashboardSubtitle: 'Your home base - stats, courses, quick actions',
    userManualDashboardBody: 'The Dashboard is the first page you see after signing in. It shows you your study snapshot at a glance and provides one-click navigation to every major tool.',
    userManualDashboardFeatureCoursesBody: 'Live count of courses synced from your Classroom account.',
    userManualDashboardFeatureStreakBody: 'Tracks consecutive days you log in and study.',
    userManualDashboardFeatureInteractionsBody: 'Total count of summaries, quizzes, chats, and evaluations you run.',
    userManualDashboardQuickActionsIntro: 'Four shortcut cards at the bottom let you jump directly into:',
    userManualDashboardQuickActionChat: 'Chat page',
    userManualDashboardQuickActionSummarize: 'Summariser page',
    userManualDashboardQuickActionTakeQuiz: 'Quiz Generator (take tab)',
    userManualDashboardQuickActionGradeEssay: 'Essay Grader',
    userManualDashboardSyncTitle: 'Google Classroom Sync',
    userManualDashboardSyncBody: 'If you signed in with Google, the dashboard automatically syncs your courses on load (with a 5-minute cooldown to avoid hammering the API). You can also trigger a manual sync with the Sync Classroom button. New documents get auto-summarised and auto-quizzed in the background - you will receive a toast notification when they are ready.',
    userManualDashboardSyncTip: 'On first login, a modal will ask which courses you want auto-processed. You can change these preferences at any time by clicking Sync Classroom.',
    userManualCoursesTitle: 'Courses',
    userManualCoursesSubtitle: 'Browse your synced materials and download PDFs',
    userManualCoursesBody: 'The Courses page is a master-detail file browser for all your synced course materials. Select a course on the left to see all its documents on the right.',
    userManualCoursesSearchTitle: 'Course Search',
    userManualCoursesSearchBody: 'Filter your courses in real-time by title using the search bar.',
    userManualCoursesPreviewTitle: 'Preview',
    userManualCoursesPreviewBody: 'View PDFs inside a full-screen.',
    userManualCoursesDownloadTitle: 'Secure Download',
    userManualCoursesDownloadBody: 'Download PDFs directly. Google Drive files are resolved automatically.',
    userManualCoursesDocTypesTitle: 'Document Types',
    userManualCoursesDocTypeMaterialLabel: 'Material / Coursework',
    userManualCoursesDocTypeMaterialBody: 'PDFs with Preview and Download buttons',
    userManualCoursesDocTypeAnnouncementLabel: 'Announcement / Post',
    userManualCoursesDocTypeAnnouncementBody: 'Text-only items showing their body content',
    userManualCoursesDocTypeManualUploadLabel: 'Manual Upload',
    userManualCoursesDocTypeManualUploadBody: 'Files you upload yourself through any AI tool',
    userManualAgentsTitle: 'AI Agents Hub',
    userManualAgentsSubtitle: 'The central launchpad for all five AI tools',
    userManualAgentsBody: 'The AI Agents page is an interactive orbital UI showing all five AI tools arranged around a central brain icon. Click any node to launch that tool with a ripple animation. Hover over a node to read a brief description of what it does before clicking.',
    userManualAgentsEssayDesc: 'Predicts an IELTS band score (0-9) for any essay.',
    userManualAgentsEvaluatorDesc: 'Scores a student summary against lecture material on 6 metrics.',
    userManualAgentsSummarizerDesc: 'Generates a structured AI summary of any document or pasted text.',
    userManualAgentsChatDesc: 'Ask questions about your course material in a conversational interface.',
    userManualAgentsQuizDesc: 'Generates and lets you take MCQ/True-False quizzes from course material.',
    userManualSummarizerSubtitle: 'AI-generated summaries of your lecture material',
    userManualSummarizerBody: 'Paste lecture text, or pick a document from one of your synced courses, and the AI will return a clean structured summary broken into key topics.',
    userManualSummarizerInputTitle: 'Input Options',
    userManualSummarizerInputPasteLabel: 'Paste Text',
    userManualSummarizerInputPasteBody: 'Paste lecture notes or any text directly',
    userManualSummarizerInputChooseLabel: 'Choose Document',
    userManualSummarizerInputChooseBody: 'Select a course, then pick a synced PDF',
    userManualSummarizerInputUploadLabel: 'Upload PDF',
    userManualSummarizerInputUploadBody: 'Upload a file from your device',
    userManualSummarizerAutoTitle: 'Auto-Summarize on Sync',
    userManualSummarizerAutoBody: 'When the Dashboard syncs new materials, the system can automatically queue summaries in the background for any course you opted in to. A toast appears when they are ready and you can find them under the relevant document in your Courses page.',
    userManualQuizSubtitle: 'Generate and take quizzes from your course material',
    userManualQuizBody: 'The Quiz Generator has two tabs: Generate and Take Quiz.',
    userManualQuizGenerateTitle: 'Generate Tab',
    userManualQuizGenerateItem1: 'Choose a course and document, or paste text / upload a PDF',
    userManualQuizGenerateItem2: 'Select question type: MCQ (multiple choice) or True/False',
    userManualQuizGenerateItem3: 'Set the number of questions you want generated',
    userManualQuizGenerateItem4: 'Click Generate - the AI creates a quiz stored under that document',
    userManualQuizTakeTitle: 'Take Quiz Tab',
    userManualQuizTakeItem1: 'Browse all previously generated quizzes by course and document',
    userManualQuizTakeItem2: 'Answer each question and submit to see your score and correct answers',
    userManualQuizTakeItem3: 'Your quiz-taking count is tracked in the Dashboard AI Interactions stat',
    userManualQuizTip: 'Quizzes can also be auto-generated during Classroom sync for opted-in courses.',
    userManualChatSubtitle: 'Conversational AI grounded in your course material',
    userManualChatBody: 'The Chat page gives you a real-time conversation with an AI tutor that has context about your selected course material. Ask it to explain concepts, quiz you verbally, or clarify anything confusing from your lectures.',
    userManualChatHowTitle: 'How to use it',
    userManualChatHowItem1: 'Select a course and optionally a specific document to focus the AI context',
    userManualChatHowItem2: 'Type your question and press Enter or click Send',
    userManualChatHowItem3: 'The AI responds in Markdown - code blocks, lists, and bold text are all rendered',
    userManualChatHowItem4: 'The conversation history is preserved within the session',
    userManualEvaluatorSubtitle: 'Score a student summary against lecture material',
    userManualEvaluatorBody: 'The Evaluator compares a student summary to the original lecture material and scores it across 6 dimensions, each out of 10.',
    userManualEvaluatorMetricCorrectness: 'Correctness',
    userManualEvaluatorMetricCorrectnessDesc: 'Are the facts accurate?',
    userManualEvaluatorMetricRelevance: 'Relevance',
    userManualEvaluatorMetricRelevanceDesc: 'Does it stick to what matters?',
    userManualEvaluatorMetricCoherence: 'Coherence',
    userManualEvaluatorMetricCoherenceDesc: 'Does it flow logically?',
    userManualEvaluatorMetricCompleteness: 'Completeness',
    userManualEvaluatorMetricCompletenessDesc: 'Are key points covered?',
    userManualEvaluatorMetricConciseness: 'Conciseness',
    userManualEvaluatorMetricConcisenessDesc: 'Is it appropriately brief?',
    userManualEvaluatorMetricTerminology: 'Terminology',
    userManualEvaluatorMetricTerminologyDesc: 'Is domain vocabulary used correctly?',
    userManualEvaluatorInputTitle: 'Input Options',
    userManualEvaluatorInputLectureLabel: 'Lecture source',
    userManualEvaluatorInputLectureBody: 'paste text, or pick a synced document from a course',
    userManualEvaluatorInputStudentLabel: 'Student summary',
    userManualEvaluatorInputStudentBody: 'type it in or upload a PDF',
    userManualEvaluatorResults: 'Results show an overall score, word counts for both texts, a metric breakdown table with visual progress bars, and optional technical detail mode.',
    userManualEssaySubtitle: 'IELTS band prediction for student essays',
    userManualEssayBody: 'The Essay Grader uses AI to predict an IELTS writing band score (0-9) for any essay. Optionally provide the exam question for a more accurate evaluation.',
    userManualEssayWorkflowTitle: 'Workflow',
    userManualEssayWorkflowItem1: 'Paste the essay question in the left panel (optional but recommended)',
    userManualEssayWorkflowItem2: 'Either type/paste the essay text, or switch to PDF upload mode',
    userManualEssayWorkflowItem3: 'Click Predict Band - results appear in seconds',
    userManualEssayResultTitle: 'Result',
    userManualEssayResultItem1Label: 'Predicted Band',
    userManualEssayResultItem1Body: 'shown as a large score out of 9 (color-coded green/amber/red)',
    userManualEssayResultItem2Label: 'Objective',
    userManualEssayResultItem2Body: 'the grading objective the AI used to evaluate',
    userManualEssayResultItem3Label: 'Response time',
    userManualEssayResultItem3Body: 'shown as a badge so you know how long the AI took',
    userManualEssayTip: 'Band 7.5+ is shown in green, 5.5-7.4 in amber, and below 5.5 in red.',
    userManualPomodoroTitle: 'Pomodoro Timer',
    userManualPomodoroSubtitle: 'Focus sessions with automatic break tracking',
    userManualPomodoroBody: 'The Pomodoro timer runs persistently in the background across the whole app - you can switch to other pages and the timer keeps running. The sidebar shows a live progress ring on the Pomodoro icon when a session is active.',
    userManualPomodoroControlsTitle: 'Controls',
    userManualPomodoroControlStartPauseLabel: 'Start / Pause',
    userManualPomodoroControlStartPauseBody: 'toggle the current session',
    userManualPomodoroControlResetLabel: 'Reset',
    userManualPomodoroControlResetBody: 'reset to the start of the current mode',
    userManualPomodoroControlSkipLabel: 'Skip Break',
    userManualPomodoroControlSkipBody: 'visible only during break; skips to next work session',
    userManualPomodoroControlAutoLabel: 'Auto-start next',
    userManualPomodoroControlAutoBody: 'toggle to automatically start the next session when one ends',
    userManualPomodoroSettingsTitle: 'Settings',
    userManualPomodoroSettingsBody: 'Adjust work session length (default 25 min) and break length (default 5 min) using the +/- controls. Changes take effect on the next session.',
    userManualPomodoroProgressTitle: 'Progress and Streak Bonus',
    userManualPomodoroProgressBody: 'Completed cycles and a streak bonus are tracked per session. The bonus is added to your day streak score in the Dashboard stats.',
    userManualPomodoroTip: 'The timer is the key to unlocking Mini Games. The Mini Games tab is locked until the Pomodoro enters break mode.',
    userManualMiniGamesSubtitle: 'Brain breaks - only available during Pomodoro breaks',
    userManualMiniGamesLockNotice: 'The Mini Games tab is locked in the sidebar unless the Pomodoro timer is currently in break mode. This is intentional - games are a reward for finishing a focus session.',
    userManualMiniGamesAvailableTitle: 'Available Games',
    userManualMiniGamesPuzzleTitle: '8-Puzzle (Slide Puzzle)',
    userManualMiniGamesPuzzleBody: 'Rearrange numbered tiles into order by sliding them into the empty space. Tracks move count.',
    userManualMiniGamesMemoryTitle: 'Memory Match',
    userManualMiniGamesMemoryBody: 'Flip cards and find matching pairs. Uses Italian Brainrot character images. Coming soon.',
    userManualMiniGamesReactionTitle: 'Reaction Clicker',
    userManualMiniGamesReactionBody: 'Test your reaction speed. Coming soon.',
    userManualMiniGamesOutro: 'When the break ends, the Mini Games page automatically closes and you are redirected back to the Pomodoro page to start your next focus session.',
    userManualProfileSubtitle: 'Your account info and study statistics',
    userManualProfileBody: 'The Profile page shows your account details and an overview of your activity stats accumulated across all sessions.',
    userManualProfileFindTitle: 'What you will find',
    userManualProfileFindItem1: 'Display name, email, and account type (Google or Local)',
    userManualProfileFindItem2: 'Total summaries generated, quizzes created and taken, essays graded, chat sessions',
    userManualProfileFindItem3: 'Current day streak and best streak',
    userManualProfileFindItem4: 'Option to change display name (for local accounts)',
    coursePreview: 'Preview',
    courseDownload: 'Download',
    coursePdfDocument: 'PDF Document',
    coursePdfPreviewTitle: 'PDF Preview',
    profileRankProgression: 'Rank Progression',
    profileRankLabel: 'Rank',
    profileRankCopper: 'Copper',
    profileRankBronze: 'Bronze',
    profileRankSilver: 'Silver',
    profileRankGold: 'Gold',
    profileRankPlatinum: 'Platinum',
    profileRankEmerald: 'Emerald',
    profileRankDiamond: 'Diamond',
    profileRankChampion: 'Champion',
    profileRankGrandChampion: 'Grand Champion',
    profileRankLegend: 'Legend',
    profileLanguageEnglish: 'English',
    profileLanguageArabic: 'Arabic',
  },
  ar: {
    greetingMorning: 'صباح الخير',
    greetingAfternoon: 'مساء الخير',
    greetingEvening: 'مساء النور',
    greetingFallback: 'هناك',
    dateLocale: 'ar-SA',
    activeCourses: 'الدورات النشطة',
    dayStreak: 'سلسلة الأيام',
    aiInteractions: 'تفاعلات الذكاء الاصطناعي',
    yourCourses: 'دوراتك',
    syncClassroom: 'مزامنة الصف',
    syncing: 'جارٍ المزامنة...',
    noCoursesTitle: 'لا توجد دورات',
    noCoursesBody: 'لوحة التحكم فارغة. اضغط "مزامنة الصف" لجلب الدورات من Google.',
    quickActions: 'إجراءات سريعة',
    askAi: 'اسأل الذكاء الاصطناعي',
    askAiDesc: 'مساعدة فورية من المساعد التعليمي',
    summarize: 'تلخيص',
    summarizeDesc: 'اختصار ملاحظات المحاضرة فورًا',
    takeQuiz: 'ابدأ اختبارًا',
    takeQuizDesc: 'اختبر معرفتك بأسئلة الذكاء الاصطناعي',
    gradeEssay: 'تقييم المقال',
    gradeEssayDesc: 'توقع درجة IELTS الخاصة بك',
    lightMode: 'فاتح',
    darkMode: 'داكن',
    language: 'اللغة',
    navHome: 'الرئيسية',
    navCourses: 'الدورات',
    navAiAgents: 'وكلاء الذكاء الاصطناعي',
    navFocusBreak: 'التركيز والاستراحة',
    navPomodoro: 'بومودورو',
    navMiniGames: 'ألعاب صغيرة',
    navSupport: 'الدعم',
    navUserManual: 'دليل المستخدم',
    signOut: 'تسجيل الخروج',
    availableDuringBreak: 'متاح أثناء الاستراحة',
    backToAiAgents: 'العودة لوكلاء الذكاء الاصطناعي',
    myCourses: 'دوراتي',
    searchCourses: 'ابحث عن الدورات...',
    noCoursesMatch: 'لا توجد دورات مطابقة لبحثك.',
    noCourseSelected: 'لم يتم اختيار دورة',
    noCourseSelectedBody: 'اختر دورة من القائمة الجانبية لعرض المواد والواجبات الرسمية.',
    courseMaterials: 'مواد الدورة',
    files: 'ملفات',
    folderEmpty: 'المجلد فارغ',
    folderEmptyBody: 'لم تتم مزامنة أي مستندات من Google Classroom لهذه الدورة بعد.',
    coursesLoadError: 'تعذر تحميل الدورات. يرجى المحاولة مرة أخرى.',
    downloadError: 'تعذر تنزيل المستند.',
    previewError: 'تعذر تحميل معاينة المستند.',
    backToDashboard: 'العودة إلى لوحة التحكم',
    signInTagline: 'رفيق تعلّم شخصي مدعوم بالذكاء الاصطناعي لتحسين رحلتك التعليمية.',
    signInButton: 'المتابعة باستخدام Google',
    aiAgentLabel: 'وكيل ذكاء اصطناعي',
    aiAgentsSubtitle: 'اختر وكيلاً للبدء',
    aiAgentsHint: 'اختر وكيلاً للبدء • مرّر للمعاينة',
    aiSummarizerTitle: 'الملخص',
    aiSummarizerContent: 'حوّل ملاحظات المحاضرة الطويلة إلى ملخصات قصيرة جاهزة للاختبار.',
    aiQuizTitle: 'مولد الاختبارات',
    aiQuizContent: 'أنشئ اختبارات تدريبية من النصوص أو وثائق المقرر.',
    aiChatTitle: 'محادثة المساعد الذكي',
    aiChatContent: 'اسأل أسئلة متابعة واحصل على شرح فوري للمفاهيم.',
    aiEvaluatorTitle: 'المقيّم',
    aiEvaluatorContent: 'قيّم جودة الملخص واحصل على ملاحظات منظمة.',
    aiEssayTitle: 'مصحح المقال',
    aiEssayContent: 'توقع درجة IELTS واحصل على إرشادات للكتابة.',
    navProfile: 'الملف الشخصي',
    profileKicker: 'ملف الدراسة',
    profileTitleFallback: 'طالب',
    profileSubtitle: 'مركز تعلمك وملخص التقدم.',
    profileTotalInteractions: 'إجمالي التفاعلات',
    profileStreakBonus: 'مكافأة السلسلة',
    profileAchieved: 'تم تحقيقه',
    profileAchievements: 'الإنجازات',
    profileAchievementsHint: 'تحديثات التقدم يومياً',
    profileAchievementStreak: 'سلسلة لمدة 3 أيام',
    profileAchievementStreak7: 'سلسلة لمدة 7 أيام',
    profileAchievementStreak14: 'سلسلة لمدة 14 يومًا',
    profileAchievementSummaries: 'ملخصات مُنشأة',
    profileAchievementSummaries10: '10 ملخصات مُنشأة',
    profileAchievementQuizzes: 'اختبارات مُنشأة',
    profileAchievementQuizzes10: '10 اختبارات مُنشأة',
    profileAchievementFocus: 'دورات تركيز',
    profileAchievementFocus10: '10 دورات تركيز',
    profileAchievementChats20: '20 محادثة مع المساعد',
    profileAchievementEssays5: '5 مقالات تم تقييمها',
    profileAchievementEvaluations5: '5 تقييمات مكتملة',
    profileTaskDailySummariesTitle: 'تلخيص مرتين',
    profileTaskDailySummariesDesc: 'أنشئ ملخصين اليوم',
    profileTaskDailyQuizTitle: 'دقة الاختبار',
    profileTaskDailyQuizDesc: 'أجب عن 5 أسئلة اختبار بشكل صحيح',
    profileTaskDailyFocusTitle: 'جلسات التركيز',
    profileTaskDailyFocusDesc: 'أكمل دورتين بومودورو',
    profileTaskDailyTutorTitle: 'اسأل المساعد',
    profileTaskDailyTutorDesc: 'أرسل 3 أسئلة للمساعد',
    profileTaskDailyEssayTitle: 'تقييم مقال',
    profileTaskDailyEssayDesc: 'قدّم مقالًا واحدًا للتقييم',
    profileTaskDailyEvaluationTitle: 'تقييم ملخص',
    profileTaskDailyEvaluationDesc: 'أجرِ تقييمًا واحدًا للملخص',
    profileActiveCourses: 'الدورات النشطة',
    profileStreak: 'سلسلة الأيام',
    profileFocusHours: 'ساعات التركيز',
    profileCompletedCycles: 'الدورات المكتملة',
    profileLearningProfile: 'ملف التعلم',
    profileLoadingCourses: 'جارٍ تحميل المقررات...',
    profileNoCourses: 'لا توجد دورات بعد. قم بالمزامنة أو أنشئ دورة للبدء.',
    profileNextAction: 'الإجراء التالي',
    profileOpenCourse: 'افتح المقرر',
    profileSettings: 'إعدادات الحساب',
    profileTheme: 'السمة',
    profileThemeDark: 'داكن',
    profileThemeLight: 'فاتح',
    profileLanguage: 'اللغة',
    profileNotifications: 'الإشعارات',
    automationTitle: 'تفضيلات الأتمتة',
    automationBody: 'اختر المقررات التي تريد تشغيل الأتمتة عليها.',
    automationAllCourses: 'كل المقررات',
    automationEmpty: 'لا توجد مقررات بعد. قم بالمزامنة أو أنشئ مقررًا أولًا.',
    automationSelectionHint: 'اختر مقررًا واحدًا على الأقل أو حدّد "كل المقررات".',
    automationSave: 'حفظ إعدادات الأتمتة',
    automationSaved: 'تم الحفظ',
    automationModalTitle: 'اختر المقررات للأتمتة',
    automationModalBody: 'حدد المقررات التي تريد أتمتتها. يمكنك تعديل ذلك لاحقًا من إعدادات الملف الشخصي.',
    automationModalCta: 'حفظ والمتابعة',
    profileNextSummary: 'أنشئ أول ملخص',
    profileNextQuiz: 'انشئ اختبارًا',
    profileNextFocus: 'ابدأ جلسة تركيز',
    profileNextReview: 'مراجعة نتيجة حديثة',
    profileTaskReward: 'المكافأة',
    profileXp: 'الخبرة',
    profileLevel: 'المستوى',
    profileNextLevel: 'المستوى التالي عند',
    profileRankFallback: 'بدون رتبة',
    profileDailyTasks: 'مهام اليوم',
    profileTaskEmpty: 'لا توجد مهام بعد. أكمل بعض الإجراءات لفتح مهام اليوم.',
    profileLoadingTasks: 'جارٍ تحديث المهام...',
    profileTaskCompleted: 'مكتمل',
    profileTaskReward: 'المكافأة',
    profileLeaderboard: 'لوحة المتصدرين',
    profileLeaderboardEmpty: 'لا توجد بيانات ترتيب بعد.',
    timelineComplete: 'مكتمل',
    timelineInProgress: 'قيد التقدم',
    timelinePending: 'قيد الانتظار',
    timelineEnergy: 'مستوى الطاقة',
    timelineConnected: 'العُقد المرتبطة',
    chatSeed: 'ماذا نتعلم اليوم؟',
    chatHeader: 'كيف يمكنني مساعدتك؟',
    chatGeneral: 'محادثة عامة',
    chatCourseContext: 'سياق المقرر',
    chatSelectCourse: 'اختر مقرراً...',
    chatSelectDocument: 'اختر مستنداً...',
    chatAskPlaceholder: 'اطرح سؤالاً...',
    chatError: '⚠️ خطأ في الاتصال بالمحادث. يرجى اختيار مقرر إذا كنت تستخدم وضع السياق.',
    chatHistoryTab: 'السجل',
    chatHistoryTitle: 'سجل المحادثات',
    chatHistoryNew: 'محادثة جديدة',
    chatHistoryGeneralLabel: 'عام',
    chatHistoryCourseLabel: 'مقرر',
    chatHistoryEmpty: 'لا توجد محادثات بعد.',
    chatHistorySelectCourse: 'اختر مقرراً لعرض السجل.',
    chatHistoryAuth: 'سجّل الدخول لعرض السجل.',
    chatHistoryLoading: 'جارٍ تحميل السجل...',
    chatHistoryLoadError: 'تعذر تحميل السجل. حاول مرة أخرى.',
    chatHistoryPreviewEmpty: 'لا توجد رسائل بعد',
    chatTabChat: 'المحادثة',
    chatSpeak: 'تشغيل الإجابة صوتياً',
    chatMicStart: 'ابدأ التسجيل',
    chatMicStop: 'أوقف التسجيل',
    chatMicUnsupported: 'الوصول إلى الميكروفون غير مدعوم في هذا المتصفح.',
    chatMicError: 'فشل الميكروفون أو النسخ. الرجاء المحاولة مرة أخرى.',
    chatMicEmpty: 'لم يتم اكتشاف كلام. حاول مجدداً.',
    chatTranscribing: 'جارٍ نسخ الصوت…',
    chatTtsError: 'فشل تشغيل الصوت. حاول مرة أخرى.',
    quizTitle: 'محرك اختبارات الذكاء الاصطناعي',
    quizSubtitle: 'أنشئ اختبارات من موادك أو تدرب على اختبارات سابقة.',
    quizTabGenerate: 'إنشاء اختبار',
    quizTabTake: 'حل اختبار',
    quizSettings: 'إعدادات الاختبار',
    quizSourceDocument: 'مستند',
    quizSourceUpload: 'رفع ملف',
    quizSourceText: 'نص',
    quizCourseLabel: 'ربط المقرر',
    quizLoadingCourses: 'جارٍ تحميل المقررات…',
    quizSelectDocument: 'اختر مستنداً',
    quizLoading: 'جارٍ التحميل...',
    quizNoDocs: 'لا توجد مستندات',
    quizChooseDocument: 'اختر مستنداً...',
    quizUploadBrowse: 'اضغط لتصفح PDF',
    quizPasteTextLabel: 'ألصق النص',
    quizPasteTextPlaceholder: 'ألصق ملاحظات المحاضرة هنا...',
    quizQuestionsLabel: 'الأسئلة',
    quizOptionsLabel: 'الخيارات',
    quizGenerating: 'جارٍ الإنشاء...',
    quizBuild: 'إنشاء اختبار',
    quizSaved: 'تم حفظ الاختبار! ستجده في تبويب "حل اختبار".',
    quizEphemeral: 'تم إنشاء اختبار مؤقت! (غير محفوظ في قاعدة البيانات).',
    quizEmptyState: 'اضبط الإعدادات وأنشئ اختباراً لبدء التدريب.',
    quizYourQuizzes: 'اختباراتك',
    quizLoadingQuizzes: 'جارٍ تحميل الاختبارات...',
    quizNoQuizzes: 'لا توجد اختبارات لهذا المقرر بعد.',
    quizLabel: 'اختبار',
    quizTakeQuiz: 'ابدأ الاختبار',
    quizBackToQuizzes: 'العودة للاختبارات',
    quizRevealAnswers: 'إظهار النتيجة',
    quizReset: 'إعادة ضبط',
    quizScoreLabel: 'النتيجة',
    quizAnswerLabel: 'الإجابة',
    quizDataNotFound: 'لا توجد بيانات',
    quizGenerationFailed: 'فشل إنشاء الاختبار.',
    summarizerTitle: 'ملخص الذكاء الاصطناعي',
    summarizerSubtitle: 'حوّل مواد المحاضرة الطويلة أو ملفات PDF إلى ملاحظات موجزة.',
    summarizerConfig: 'الإعدادات',
    summarizerSourceDocument: 'مستند المقرر',
    summarizerSourceUpload: 'رفع ملف بي دي اف',
    summarizerSelectCourse: 'اختر المقرر',
    summarizerChooseCourse: 'اختر مقرراً...',
    summarizerSelectDocument: 'اختر المستند',
    summarizerSelectCourseFirst: 'اختر المقرر أولاً',
    summarizerNoDocs: 'لا توجد مستندات',
    summarizerChooseDocument: 'اختر مستنداً...',
    summarizerClickBrowse: 'اضغط لتصفح PDF',
    summarizerProcessedMemory: 'تتم المعالجة في الذاكرة دون حفظ.',
    summarizerProcessing: 'جارٍ المعالجة...',
    summarizerGenerate: 'إنشاء الملخص',
    summarizerOutput: 'مخرجات الملخص',
    summarizerEmpty: 'اختر المصدر واضغط إنشاء لعرض ملخص الذكاء الاصطناعي هنا.',
    summarizerError: 'تعذر إنشاء الملخص. يرجى التحقق من اتصال الخادم.',
    summarizerTabGenerate: 'إنشاء ملخص',
    summarizerTabLibrary: 'ملخصاتي',
    summarizerLibraryTitle: 'مكتبة الملخصات',
    summarizerLibrarySelectCourse: 'تصفية حسب المقرر',
    summarizerLibraryAllCourses: 'كل المقررات',
    summarizerLibraryLoading: 'جارٍ تحميل الملخصات...',
    summarizerLibraryEmpty: 'لا توجد ملخصات بعد.',
    summarizerLibrarySelectHint: 'اختر ملخصاً لعرضه.',
    summarizerLibraryRefresh: 'تحديث',
    summarizerLibraryError: 'تعذر تحميل الملخصات.',
    syncNewDocTitle: 'تمت مزامنة مستند جديد',
    syncSummaryQueuedTitle: 'جاري تحضير الملخص',
    syncSummaryQueuedContent: 'يتم تجهيز الملخص في الخلفية.',
    syncSummaryReadyTitle: 'الملخص جاهز',
    syncSummaryReadyContent: 'الملخص جاهز الآن للعرض.',
    syncSummaryQueuedGeneric: 'نقوم الآن بتحضير ملخصاتك الجديدة.',
    syncQuizQueuedTitle: 'جاري تحضير الاختبار',
    syncQuizQueuedContent: 'يتم تجهيز الاختبار في الخلفية.',
    syncQuizReadyTitle: 'الاختبار جاهز',
    syncQuizReadyContent: 'الاختبار جاهز الآن للحل.',
    syncQuizQueuedGeneric: 'نقوم الآن بتحضير اختباراتك الجديدة.',
    docTypeAnnouncement: 'إعلان',
    docTypePost: 'منشور',
    docTypeMaterial: 'مادة',
    docTypeCoursework: 'واجب',
    docTypeUpload: 'ملف مرفوع',
    docTypeDocument: 'مستند',
    docNoContent: 'لا يوجد محتوى متاح.',
    evaluatorCourseLabel: 'المقرر',
    evaluatorLoadingCourses: 'جارٍ تحميل المقررات…',
    evaluatorLectureTitle: 'المحاضرة / المادة المصدرية',
    evaluatorInputType: 'نوع الإدخال',
    evaluatorInputText: 'إدخال نص',
    evaluatorInputDocument: 'مستند المقرر',
    evaluatorLecturePlaceholder: 'ألصق ملاحظات المحاضرة أو المادة المصدرية…',
    evaluatorChars: 'حرف',
    evaluatorSelectDocument: 'اختر مستنداً',
    evaluatorLoadingDocuments: 'جارٍ تحميل المستندات…',
    evaluatorNoUsableDocs: 'لا توجد مستندات قابلة للاستخدام لهذا المقرر. قم بمزامنة مواد Google Classroom أولاً أو ألصق النص يدوياً.',
    evaluatorStudentSummaryTitle: 'ملخص الطالب',
    evaluatorStudentSummaryPlaceholder: 'ألصق ملخص الطالب للتقييم…',
    evaluatorSummaryInputType: 'نوع إدخال الملخص',
    evaluatorSummaryInputText: 'إدخال نص',
    evaluatorSummaryInputUpload: 'رفع ملف بي دي اف',
    evaluatorSummaryUploadBrowse: 'اضغط لتصفح PDF',
    evaluatorSummaryUploadHint: 'ارفع ملخص الطالب كملف PDF.',
    evaluatorStudentWordsUpload: 'رفع PDF',
    evaluatorEvaluating: 'جارٍ التقييم…',
    evaluatorEvaluate: 'تقييم الملخص',
    evaluatorFailed: 'فشل التقييم.',
    evaluatorOverallScore: 'النتيجة الإجمالية',
    evaluatorStudentWords: 'كلمات الطالب',
    evaluatorReferenceWords: 'كلمات المرجع',
    evaluatorKeyPoints: 'النقاط الرئيسية',
    evaluatorMetrics: 'المقاييس',
    evaluatorMetric: 'المقياس',
    evaluatorScore: 'النتيجة',
    evaluatorVisual: 'تمثيل',
    evaluatorDetails: 'التفاصيل / ملاحظات الذكاء الاصطناعي',
    metricCorrectness: 'الصحة',
    metricCorrectnessDesc: 'دمج: اتساق مع المحاضرة ومحاذاة المرجع وتطابق لغوي',
    metricRelevance: 'الملاءمة',
    metricRelevanceDesc: 'تغطية الموضوعات والأفكار الأساسية',
    metricCoherence: 'التماسك',
    metricCoherenceDesc: 'تدفق منطقي وقابلية قراءة الملخص',
    metricCompleteness: 'الاكتمال',
    metricCompletenessDesc: 'تغطية النقاط الرئيسية مع الاسترجاع مقابل المرجع',
    metricConciseness: 'الإيجاز',
    metricConcisenessDesc: 'كفاءة الطول مقارنة بالملخص المرجعي',
    metricTerminology: 'المصطلحات',
    metricTerminologyDesc: 'استخدام مفردات تخصصية للمحاضرة',
    metricHallucination: 'الهلوسة',
    metricHallucinationDesc: 'عقوبة على الادعاءات غير المدعومة في المحاضرة',
    metricMissingKeyPoints: 'نقاط رئيسية مفقودة',
    metricMissingKeyPointsDesc: 'تغطية النقاط الرئيسية المستخرجة',
    metricFactualAccuracy: 'الدقة الواقعية',
    metricFactualAccuracyDesc: 'صحة التفاصيل والادعاءات الواقعية',
    metricCriticalAnalysis: 'التحليل النقدي',
    metricCriticalAnalysisDesc: 'عمق الاستدلال والتحليل',
    essayPromptTitle: 'سؤال المقال (اختياري)',
    essayPromptPlaceholder: 'ألصق سؤال المقال إذا كان النموذج مدرباً على سياق السؤال...',
    essayInputType: 'نوع إدخال المقال',
    essayInputText: 'إدخال نص',
    essayInputUpload: 'رفع PDF',
    essayStudentEssay: 'مقال الطالب',
    essayTextPlaceholder: 'ألصق نص المقال الكامل لتوقع درجة IELTS...',
    essayUploadBrowse: 'اضغط لتصفح PDF',
    essayUploadHint: 'ارفع مقال الطالب كملف PDF.',
    essayGrading: 'جارٍ التصحيح...',
    essayPredict: 'توقع درجة IELTS',
    essayEnterTextHint: 'أدخل نص مقال الطالب لتمكين التصحيح.',
    essayPredictedBand: 'درجة IELTS المتوقعة',
    essayObjective: 'الهدف',
    essayFailed: 'فشل تصحيح المقال.',
    pomodoroKicker: 'تركيز الإنتاجية',
    pomodoroBreak: 'وقت الاستراحة',
    pomodoroFocus: 'جلسة تركيز',
    pomodoroStart: 'ابدأ',
    pomodoroPause: 'إيقاف مؤقت',
    pomodoroReset: 'إعادة ضبط',
    pomodoroSkipBreak: 'تخطي الاستراحة',
    pomodoroModeWork: 'عمل',
    pomodoroModeBreak: 'استراحة',
    pomodoroAutoStart: 'البدء التلقائي للجلسة التالية',
    pomodoroSessionSettings: 'إعدادات الجلسة',
    pomodoroWorkSession: 'جلسة عمل',
    pomodoroShortBreak: 'استراحة قصيرة',
    pomodoroMinutes: 'دقائق',
    pomodoroProgressBonus: 'مكافأة التقدم',
    pomodoroCompletedCycles: 'الدورات المكتملة',
    pomodoroStreakBonus: 'مكافأة السلسلة',
    pomodoroNote: 'كل دورة تركيز كاملة تضيف +10 نقاط للسلسلة.',
    miniLockedTitle: 'الألعاب الصغيرة مقفلة',
    miniLockedBody: 'هذا التبويب متاح فقط أثناء استراحات بومودورو.',
    miniMemoryMatch: 'مطابقة الذاكرة',
    miniReset: 'إعادة ضبط',
    miniMoves: 'الحركات',
    miniCompleted: 'اكتملت!',
    miniPuzzle: 'لغز 8',
    miniSolved: 'تم الحل!',
    miniPlay: 'ابدأ اللعب',
    miniBackToGames: 'العودة للألعاب',
    miniBreakMode: 'وضع الاستراحة نشط',
    miniRelax: 'استمتع بألعاب صغيرة',
    miniBreakEnds: 'تنتهي الاستراحة خلال',
    miniUnavailable: 'غير متاح مؤقتاً.',
    miniSlideTiles: 'حرّك البلاطات لترتيبها من 1 إلى 8.',
    miniReactionClicker: 'نقر رد الفعل',
    miniComingSoon: 'سيتم إضافته قريباً',
    miniEmptyTile: 'بلاطة فارغة',
    miniTile: 'بلاطة',
    focusHubTitle: 'مركز التركيز',
    tabFocusTimer: 'مؤقت التركيز',
    tabMiniGames: 'ألعاب صغيرة',
    dailyGoal: 'الهدف اليومي',
    todayFocus: 'اليوم',
    sessionTimeline: 'الجدول الزمني للجلسات',
    focusGoalLabel: 'الهدف',
    noSessionsYet: 'لا توجد جلسات اليوم بعد',
    keyboardHintSpace: 'مسافة للبدء/الإيقاف',
    keyboardHintR: 'R لإعادة الضبط',
    gamesLockedHint: 'أكمل جلسة تركيز لفتح الألعاب أثناء استراحتك',
    minutesShort: 'د',
    hoursShort: 'س',
    focusQuote1: 'سر التقدم هو البدء.',
    focusQuote2: 'ركّز على الإنتاجية بدلاً من الانشغال.',
    focusQuote3: 'تحسينات يومية صغيرة تقود لنتائج مذهلة.',
    focusQuote4: 'تركيزك يحدد واقعك.',
    focusQuote5: 'العمل العميق هو القوة الخارقة للقرن الحادي والعشرين.',
    focusQuote6: 'الانضباط هو اختيار ما تريده أكثر على ما تريده الآن.',
    miniMemoryDesc: 'طابق البطاقات لاختبار ذاكرتك.',
    miniMemoryCardAlt: 'بطاقة ذاكرة',
    miniGamesPageTitle: 'ألعاب صغيرة',
    miniGamesPageSubtitle: 'خذ استراحة ذهنية مع ألعاب ممتعة',
    miniBackToTimer: 'العودة لمؤقت التركيز',
    miniGoToGames: 'العب ألعاب صغيرة',
    miniBreakCta: 'لقد استحققت استراحة! استرخِ مع لعبة سريعة.',
    miniStartFocusFirst: 'ابدأ جلسة تركيز لفتح الألعاب',
    reactionTitle: 'نقر رد الفعل',
    reactionDesc: 'اختبر ردة فعلك! انقر بأسرع ما يمكنك.',
    reactionWait: 'انتظر اللون الأخضر...',
    reactionGo: 'انقر الآن!',
    reactionTooEarly: 'مبكر جداً! انقر للمحاولة مرة أخرى',
    reactionResult: 'وقت ردة فعلك',
    reactionMs: 'مللي ثانية',
    reactionBest: 'الأفضل',
    reactionAverage: 'المتوسط',
    reactionRound: 'الجولة',
    reactionPlayAgain: 'العب مرة أخرى',
    reactionRatingLightning: 'سريع كالبرق!',
    reactionRatingFast: 'ردة فعل سريعة!',
    reactionRatingGood: 'ردة فعل جيدة!',
    reactionRatingSlow: 'واصل التدريب!',
    manualKicker: 'دليل المنصة',
    manualTitle: 'دليل استخدام مساعد التدريس متعدد الوكلاء',
    manualLead: 'تم بناء هذا الموقع لمساعدة الطلاب على الدراسة بشكل أسرع وأذكى عبر دمج عدة أدوات ذكاء اصطناعي في سير عمل واحد. الهدف الرئيسي هو دعم التعلم من مواد الصف عبر التلخيص، وتدريب الاختبارات، والمحادثات التعليمية، وتقييم الكتابة.',
    manualPurposeTitle: 'الهدف الأساسي للموقع',
    manualPurposeList1: 'تجميع محتوى المقررات وأدوات التعلم الذكية في منصة واحدة.',
    manualPurposeList2: 'تحويل مواد الدراسة إلى ملخصات واختبارات وشروحات موجهة.',
    manualPurposeList3: 'تحسين الفهم والحفظ وأداء الكتابة عبر حلقات تغذية راجعة عملية.',
    manualPurposeList4: 'تقليل وقت الدراسة مع زيادة الثقة قبل التقييمات.',
    manualUserManualTitle: 'دليل المستخدم (التبويب الحالي)',
    manualUserManualHeading: 'دليل المستخدم',
    manualUserManualPurpose: 'هذه الصفحة هي المرجع الأساسي لاستخدام المنصة وفهم دور كل ميزة في سير الدراسة.',
    manualUserManualDescription: 'تشرح هدف الموقع ووظيفة كل تبويب جانبي وطريقة مقترحة للانتقال من الإعداد إلى المراجعة. يمكنك مشاركتها مع المستخدمين الجدد كدليل سريع.',
    manualLeftTabsTitle: 'ماذا يفعل كل تبويب جانبي',
    manualTabDashboard: 'لوحة التحكم',
    manualTabDashboardPurpose: 'نظرة عامة للصفحة الرئيسية بعد تسجيل الدخول.',
    manualTabDashboardDetail1: 'يعرض التحية والتاريخ وإحصاءات الدراسة الأساسية في مكان واحد.',
    manualTabDashboardDetail2: 'يسمح بمزامنة Google Classroom وتحديث قائمة المقررات المسجلة.',
    manualTabDashboardDetail3: 'يوفر بطاقات إجراءات سريعة لفتح المحادثة والملخص والاختبار ومصحح المقال بسرعة.',
    manualTabCourses: 'الدورات',
    manualTabCoursesPurpose: 'إدارة المقررات ومواد الدراسة.',
    manualTabCoursesDetail1: 'افتح مقررًا لعرض المواد التي تمت مزامنتها من Google Classroom.',
    manualTabCoursesDetail2: 'قم بمعاينة مستندات Drive في تبويب جديد عند الحاجة.',
    manualTabPomodoro: 'بومودورو',
    manualTabPomodoroPurpose: 'جلسات تركيز مع استراحات زمنية.',
    manualTabPomodoroDetail1: 'الدورة الافتراضية 30 دقيقة عمل + 5 دقائق استراحة مع إمكانية التعديل.',
    manualTabPomodoroDetail2: 'يتضمن بدء وإيقاف مؤقت وإعادة ضبط وتخطي الاستراحة والبدء التلقائي للجلسة التالية.',
    manualTabPomodoroDetail3: 'يتتبع الدورات المكتملة ونقاط السلسلة أثناء روتين الدراسة.',
    manualTabMiniGames: 'الألعاب الصغيرة',
    manualTabMiniGamesPurpose: 'جلسات لعب قصيرة لتجديد التركيز أثناء الاستراحة.',
    manualTabMiniGamesDetail1: 'مقفلة أثناء وضع العمل وتفتح فقط أثناء استراحة بومودورو.',
    manualTabMiniGamesDetail2: 'تتضمن حاليًا مطابقة الذاكرة مع وضع لعب بملء الشاشة.',
    manualTabMiniGamesDetail3: 'يعيدك إلى الدراسة عند انتهاء الاستراحة وإغلاق الوصول للألعاب.',
    manualTabSummarizer: 'الملخص',
    manualTabSummarizerPurpose: 'تحويل المحتوى الطويل إلى ملاحظات مختصرة.',
    manualTabSummarizerDetail1: 'ألصق النص أو اختر مستندات المقرر لإنشاء ملخصات مركزة.',
    manualTabSummarizerDetail2: 'يوفر الوقت قبل المراجعة باستخراج المفاهيم بسرعة.',
    manualTabSummarizerDetail3: 'مفيد قبل الاختبارات لإنشاء مواد مراجعة سريعة.',
    manualTabQuiz: 'مولد الاختبارات',
    manualTabQuizPurpose: 'إنشاء وحل اختبارات مولدة بالذكاء الاصطناعي.',
    manualTabQuizDetail1: 'إنشاء أسئلة اختبار من النصوص أو مواد المقرر.',
    manualTabQuizDetail2: 'تعديل عدد الأسئلة والخيارات بما يناسب المستوى.',
    manualTabQuizDetail3: 'التحويل إلى وضع حل الاختبار للتدرب على الاختبارات المحفوظة حسب المقرر.',
    manualTabChat: 'محادثة المساعد الذكي',
    manualTabChatPurpose: 'طرح الأسئلة والحصول على شروحات موجهة.',
    manualTabChatDetail1: 'استخدام التعلم الحواري لتوضيح الموضوعات خطوة بخطوة.',
    manualTabChatDetail2: 'مفيد لأسئلة المتابعة عندما تكون ملاحظات المحاضرة غير واضحة.',
    manualTabChatDetail3: 'يدعم التحقق السريع من المفاهيم أثناء الدراسة.',
    manualTabEvaluator: 'المقيّم',
    manualTabEvaluatorPurpose: 'تقييم جودة الملخص وتغطيته.',
    manualTabEvaluatorDetail1: 'مقارنة الملخصات بالمقاييس المتوقعة للجودة.',
    manualTabEvaluatorDetail2: 'يسلط الضوء على نقاط القوة والضعف لتحسين كتابة الملخص.',
    manualTabEvaluatorDetail3: 'يساعد على التحقق من حفظ المعنى الأساسي في الملاحظات.',
    manualTabEssay: 'مصحح المقال',
    manualTabEssayPurpose: 'تقدير جودة المقال باستخدام النموذج.',
    manualTabEssayDetail1: 'إرسال نص المقال والحصول على نتيجة مدعومة بالذكاء الاصطناعي.',
    manualTabEssayDetail2: 'مفيد للتدريب التكراري قبل التسليم النهائي.',
    manualTabEssayDetail3: 'يدعم التقييم الذاتي وتسريع تحسين الكتابة.',
    userManualHeroKicker: 'التوثيق',
    userManualHeroTitle: 'دليل المستخدم',
    userManualHeroLead: 'كل ما تحتاج معرفته عن Squee Learn - من مزامنة Google Classroom إلى الاستفادة القصوى من كل أداة ذكاء اصطناعي.',
    userManualOverviewTitle: 'نظرة عامة على المنصة',
    userManualOverviewSubtitle: 'ما هو Squee Learn وكيف يساعدك',
    userManualOverviewBody: 'هو مساعد تدريس متعدد الوكلاء بالذكاء الاصطناعي لمساعدة الطلاب على الدراسة بذكاء. يتصل مباشرة بـ Google Classroom لمزامنة المقررات والمستندات تلقائيا، ثم يقدم مجموعة من الأدوات الذكية التي تعمل على مواد مقرراتك الفعلية - دون الحاجة إلى النسخ واللصق يدويا.',
    userManualOverviewHighlightAgentsLabel: '5 وكلاء ذكاء اصطناعي',
    userManualOverviewHighlightAgentsBody: 'الملخص، مولد الاختبارات، محادثة المساعد الذكي، المقيّم، مصحح المقال',
    userManualOverviewHighlightSyncLabel: 'المزامنة التلقائية',
    userManualOverviewHighlightSyncBody: 'تتم مزامنة مقررات Google Classroom وملفات PDF عند كل تسجيل دخول',
    userManualOverviewHighlightFocusLabel: 'أدوات التركيز',
    userManualOverviewHighlightFocusBody: 'مؤقت بومودورو يفتح الألعاب الصغيرة أثناء الاستراحات',
    userManualOverviewHighlightProgressLabel: 'تتبع التقدم',
    userManualOverviewHighlightProgressBody: 'سلسلة الأيام، عدد تفاعلات الذكاء الاصطناعي، وإحصاءات كل جلسة',
    userManualOverviewTipLabel: 'نوعان من الحسابات:',
    userManualOverviewTipBody: 'سجّل الدخول عبر Google للحصول على مزامنة Classroom، أو أنشئ حسابا محليا وارفع ملفات PDF يدويا في أي أداة ذكاء اصطناعي. كلا النوعين يتيح الوصول الكامل لكل الميزات.',
    userManualDashboardTitle: 'لوحة التحكم',
    userManualDashboardSubtitle: 'واجهتك الرئيسية - الإحصاءات والمقررات والإجراءات السريعة',
    userManualDashboardBody: 'لوحة التحكم هي أول صفحة تراها بعد تسجيل الدخول. تعرض لمحة سريعة عن دراستك وتوفر تنقلا بنقرة واحدة لكل أداة رئيسية.',
    userManualDashboardFeatureCoursesBody: 'عدد مباشر للمقررات التي تمت مزامنتها من حساب Classroom.',
    userManualDashboardFeatureStreakBody: 'يتتبع الأيام المتتالية التي سجلت فيها الدخول ودرست.',
    userManualDashboardFeatureInteractionsBody: 'إجمالي عدد الملخصات والاختبارات والمحادثات والتقييمات التي أجريتها.',
    userManualDashboardQuickActionsIntro: 'أربع بطاقات اختصار في الأسفل تتيح لك الانتقال مباشرة إلى:',
    userManualDashboardQuickActionChat: 'صفحة المحادثة',
    userManualDashboardQuickActionSummarize: 'صفحة الملخص',
    userManualDashboardQuickActionTakeQuiz: 'مولد الاختبارات (تبويب الحل)',
    userManualDashboardQuickActionGradeEssay: 'مصحح المقال',
    userManualDashboardSyncTitle: 'مزامنة Google Classroom',
    userManualDashboardSyncBody: 'إذا سجلت الدخول عبر Google، تقوم لوحة التحكم بمزامنة المقررات تلقائيا عند التحميل (مع مهلة تهدئة 5 دقائق لتجنب الضغط على واجهة البرمجة). يمكنك أيضا تشغيل المزامنة يدويا عبر زر مزامنة الصف. تتم جدولة التلخيص والاختبارات تلقائيا في الخلفية للمستندات الجديدة - وستتلقى إشعارا عند جاهزيتها.',
    userManualDashboardSyncTip: 'عند أول تسجيل دخول، ستظهر نافذة تسألك عن المقررات التي تريد معالجتها تلقائيا. يمكنك تغيير هذه التفضيلات في أي وقت بالنقر على مزامنة الصف.',
    userManualCoursesTitle: 'الدورات',
    userManualCoursesSubtitle: 'تصفح المواد المتزامنة وحمل ملفات PDF',
    userManualCoursesBody: 'صفحة الدورات هي متصفح ملفات بنمط رئيسي-تفصيلي لكل موادك المتزامنة. اختر مقررا على اليسار لعرض مستنداته على اليمين.',
    userManualCoursesSearchTitle: 'بحث المقررات',
    userManualCoursesSearchBody: 'فلتر المقررات لحظيا حسب العنوان باستخدام شريط البحث.',
    userManualCoursesPreviewTitle: 'معاينة',
    userManualCoursesPreviewBody: 'عرض ملفات PDF داخل شاشة كاملة.',
    userManualCoursesDownloadTitle: 'تنزيل آمن',
    userManualCoursesDownloadBody: 'نزّل ملفات PDF مباشرة. يتم حل ملفات Google Drive تلقائيا.',
    userManualCoursesDocTypesTitle: 'أنواع المستندات',
    userManualCoursesDocTypeMaterialLabel: 'مواد / واجبات',
    userManualCoursesDocTypeMaterialBody: 'ملفات PDF مع أزرار معاينة وتنزيل',
    userManualCoursesDocTypeAnnouncementLabel: 'إعلان / منشور',
    userManualCoursesDocTypeAnnouncementBody: 'عناصر نصية تعرض محتواها',
    userManualCoursesDocTypeManualUploadLabel: 'رفع يدوي',
    userManualCoursesDocTypeManualUploadBody: 'ملفات رفعتها بنفسك عبر أي أداة ذكاء اصطناعي',
    userManualAgentsTitle: 'مركز وكلاء الذكاء الاصطناعي',
    userManualAgentsSubtitle: 'منصة إطلاق مركزية لكل أدوات الذكاء الاصطناعي الخمس',
    userManualAgentsBody: 'صفحة وكلاء الذكاء الاصطناعي واجهة مدارية تفاعلية تعرض الأدوات الخمس حول أيقونة دماغ مركزية. انقر أي عقدة لتشغيل الأداة مع حركة تموج. مرر فوق العقدة لقراءة وصف مختصر قبل النقر.',
    userManualAgentsEssayDesc: 'يتنبأ بدرجة IELTS (0-9) لأي مقال.',
    userManualAgentsEvaluatorDesc: 'يقيم ملخص الطالب مقابل مادة المحاضرة وفق 6 مقاييس.',
    userManualAgentsSummarizerDesc: 'ينشئ ملخصا منظما بالذكاء الاصطناعي لأي مستند أو نص ملصق.',
    userManualAgentsChatDesc: 'اطرح أسئلة حول مواد مقررك عبر واجهة محادثة.',
    userManualAgentsQuizDesc: 'ينشئ اختبارات اختيار من متعدد وصح/خطأ ويتيح حلها من مواد المقرر.',
    userManualSummarizerSubtitle: 'ملخصات بالذكاء الاصطناعي لمواد المحاضرات',
    userManualSummarizerBody: 'الصق نص المحاضرة أو اختر مستندا من أحد مقرراتك المتزامنة، وسيعيد الذكاء الاصطناعي ملخصا منظما ومقسما إلى موضوعات رئيسية.',
    userManualSummarizerInputTitle: 'خيارات الإدخال',
    userManualSummarizerInputPasteLabel: 'لصق نص',
    userManualSummarizerInputPasteBody: 'الصق ملاحظات المحاضرة أو أي نص مباشرة',
    userManualSummarizerInputChooseLabel: 'اختيار مستند',
    userManualSummarizerInputChooseBody: 'اختر المقرر ثم حدد ملف PDF متزامنا',
    userManualSummarizerInputUploadLabel: 'رفع PDF',
    userManualSummarizerInputUploadBody: 'ارفع ملفا من جهازك',
    userManualSummarizerAutoTitle: 'التلخيص التلقائي عند المزامنة',
    userManualSummarizerAutoBody: 'عند مزامنة مواد جديدة من لوحة التحكم، يمكن للنظام جدولة تلخيصات تلقائية في الخلفية لأي مقرر اشتركت به. يظهر إشعار عندما تصبح جاهزة ويمكنك العثور عليها ضمن المستند المناسب في صفحة الدورات.',
    userManualQuizSubtitle: 'أنشئ اختبارات وحلها من مواد مقررك',
    userManualQuizBody: 'مولد الاختبارات يحتوي على تبويبين: إنشاء وحل الاختبار.',
    userManualQuizGenerateTitle: 'تبويب الإنشاء',
    userManualQuizGenerateItem1: 'اختر مقررا ومستندا، أو الصق نصا / ارفع PDF',
    userManualQuizGenerateItem2: 'اختر نوع السؤال: اختيار من متعدد أو صح/خطأ',
    userManualQuizGenerateItem3: 'حدد عدد الأسئلة التي تريد إنشاءها',
    userManualQuizGenerateItem4: 'اضغط إنشاء - ينشئ الذكاء الاصطناعي اختبارا محفوظا تحت ذلك المستند',
    userManualQuizTakeTitle: 'تبويب حل الاختبار',
    userManualQuizTakeItem1: 'تصفح كل الاختبارات التي تم إنشاؤها حسب المقرر والمستند',
    userManualQuizTakeItem2: 'أجب عن كل سؤال ثم أرسل لرؤية نتيجتك والإجابات الصحيحة',
    userManualQuizTakeItem3: 'يتم تتبع عدد مرات حل الاختبارات ضمن إحصائية تفاعلات الذكاء الاصطناعي في لوحة التحكم',
    userManualQuizTip: 'يمكن أيضا إنشاء الاختبارات تلقائيا أثناء مزامنة Classroom للمقررات التي تم تفعيلها.',
    userManualChatSubtitle: 'محادثة ذكاء اصطناعي تعتمد على مواد مقررك',
    userManualChatBody: 'تمنحك صفحة المحادثة حوارا فوريا مع معلم ذكاء اصطناعي لديه سياق عن مواد المقرر المختارة. اطلب منه شرح المفاهيم أو اختبارك شفهيا أو توضيح ما هو غير واضح في محاضراتك.',
    userManualChatHowTitle: 'طريقة الاستخدام',
    userManualChatHowItem1: 'اختر مقررا وبشكل اختياري مستندا محددا لتركيز سياق الذكاء الاصطناعي',
    userManualChatHowItem2: 'اكتب سؤالك واضغط Enter أو انقر إرسال',
    userManualChatHowItem3: 'يرد الذكاء الاصطناعي بصيغة Markdown - يتم عرض الكتل البرمجية والقوائم والنص الغامق',
    userManualChatHowItem4: 'يتم حفظ سجل المحادثة داخل الجلسة',
    userManualEvaluatorSubtitle: 'تقييم ملخص طالب مقابل مادة المحاضرة',
    userManualEvaluatorBody: 'يقارن المقيّم ملخص الطالب بالمادة الأصلية ويمنحه درجات عبر 6 أبعاد، كل منها من 10.',
    userManualEvaluatorMetricCorrectness: 'الدقة',
    userManualEvaluatorMetricCorrectnessDesc: 'هل الحقائق دقيقة؟',
    userManualEvaluatorMetricRelevance: 'الملاءمة',
    userManualEvaluatorMetricRelevanceDesc: 'هل يركز على ما يهم؟',
    userManualEvaluatorMetricCoherence: 'الترابط',
    userManualEvaluatorMetricCoherenceDesc: 'هل يتدفق بشكل منطقي؟',
    userManualEvaluatorMetricCompleteness: 'الشمول',
    userManualEvaluatorMetricCompletenessDesc: 'هل تغطي النقاط الرئيسية؟',
    userManualEvaluatorMetricConciseness: 'الإيجاز',
    userManualEvaluatorMetricConcisenessDesc: 'هل هو موجز بشكل مناسب؟',
    userManualEvaluatorMetricTerminology: 'المصطلحات',
    userManualEvaluatorMetricTerminologyDesc: 'هل يتم استخدام مفردات المجال بشكل صحيح؟',
    userManualEvaluatorInputTitle: 'خيارات الإدخال',
    userManualEvaluatorInputLectureLabel: 'مصدر المحاضرة',
    userManualEvaluatorInputLectureBody: 'الصق نصا أو اختر مستندا متزامنا من مقرر',
    userManualEvaluatorInputStudentLabel: 'ملخص الطالب',
    userManualEvaluatorInputStudentBody: 'اكتب النص أو ارفع PDF',
    userManualEvaluatorResults: 'تعرض النتائج الدرجة الإجمالية وعدد الكلمات لكل من النصين وجدول تفصيلي بالمقاييس مع مؤشرات مرئية، إضافة إلى وضع تفاصيل تقني اختياري.',
    userManualEssaySubtitle: 'توقع درجة IELTS لمقالات الطلاب',
    userManualEssayBody: 'يستخدم مصحح المقال الذكاء الاصطناعي للتنبؤ بدرجة كتابة IELTS (0-9) لأي مقال. يمكنك إدخال سؤال الامتحان للحصول على تقييم أدق.',
    userManualEssayWorkflowTitle: 'خطوات العمل',
    userManualEssayWorkflowItem1: 'الصق سؤال المقال في اللوحة اليسرى (اختياري لكن موصى به)',
    userManualEssayWorkflowItem2: 'اكتب أو الصق نص المقال، أو بدّل إلى وضع رفع PDF',
    userManualEssayWorkflowItem3: 'انقر توقع الدرجة - تظهر النتائج خلال ثوان',
    userManualEssayResultTitle: 'النتيجة',
    userManualEssayResultItem1Label: 'الدرجة المتوقعة',
    userManualEssayResultItem1Body: 'تظهر كرقم كبير من 9 (مشفّر بالألوان أخضر/عنبر/أحمر)',
    userManualEssayResultItem2Label: 'الهدف',
    userManualEssayResultItem2Body: 'معيار التقييم الذي استخدمه الذكاء الاصطناعي',
    userManualEssayResultItem3Label: 'زمن الاستجابة',
    userManualEssayResultItem3Body: 'يظهر كشارة لتعرف مدة التقييم',
    userManualEssayTip: 'تظهر درجة 7.5 فأعلى باللون الأخضر، و5.5-7.4 بالعنبر، وأقل من 5.5 بالأحمر.',
    userManualPomodoroTitle: 'مؤقت بومودورو',
    userManualPomodoroSubtitle: 'جلسات تركيز مع تتبع تلقائي للاستراحات',
    userManualPomodoroBody: 'يعمل مؤقت بومودورو بشكل مستمر في الخلفية عبر التطبيق بالكامل - يمكنك الانتقال بين الصفحات ويستمر المؤقت بالعمل. تعرض القائمة الجانبية حلقة تقدم حية على أيقونة بومودورو عند تفعيل جلسة.',
    userManualPomodoroControlsTitle: 'عناصر التحكم',
    userManualPomodoroControlStartPauseLabel: 'بدء / إيقاف مؤقت',
    userManualPomodoroControlStartPauseBody: 'تبديل الجلسة الحالية',
    userManualPomodoroControlResetLabel: 'إعادة ضبط',
    userManualPomodoroControlResetBody: 'إرجاع الوضع إلى بدايته',
    userManualPomodoroControlSkipLabel: 'تخطي الاستراحة',
    userManualPomodoroControlSkipBody: 'يظهر فقط أثناء الاستراحة؛ ينتقل إلى جلسة العمل التالية',
    userManualPomodoroControlAutoLabel: 'بدء تلقائي للجلسة التالية',
    userManualPomodoroControlAutoBody: 'تفعيل بدء الجلسة التالية تلقائيا عند الانتهاء',
    userManualPomodoroSettingsTitle: 'الإعدادات',
    userManualPomodoroSettingsBody: 'عدّل مدة جلسة العمل (الافتراضي 25 دقيقة) ومدة الاستراحة (الافتراضي 5 دقائق) باستخدام أزرار +/-. تسري التغييرات في الجلسة التالية.',
    userManualPomodoroProgressTitle: 'التقدم ومكافأة السلسلة',
    userManualPomodoroProgressBody: 'يتم تتبع الدورات المكتملة ومكافأة السلسلة لكل جلسة. تتم إضافة المكافأة إلى نقاط سلسلة الأيام في لوحة التحكم.',
    userManualPomodoroTip: 'المؤقت هو المفتاح لفتح الألعاب الصغيرة. تبويب الألعاب الصغيرة يبقى مقفلا حتى يدخل بومودورو وضع الاستراحة.',
    userManualMiniGamesSubtitle: 'استراحات ذهنية - متاحة فقط أثناء استراحات بومودورو',
    userManualMiniGamesLockNotice: 'تبويب الألعاب الصغيرة مقفل في الشريط الجانبي ما لم يكن مؤقت بومودورو في وضع الاستراحة. هذا مقصود - الألعاب مكافأة لإنهاء جلسة تركيز.',
    userManualMiniGamesAvailableTitle: 'الألعاب المتاحة',
    userManualMiniGamesPuzzleTitle: 'لغز 8 (الأحجية المنزلقة)',
    userManualMiniGamesPuzzleBody: 'أعد ترتيب البلاطات المرقمة عبر تحريكها إلى المساحة الفارغة. يتتبع عدد الحركات.',
    userManualMiniGamesMemoryTitle: 'مطابقة الذاكرة',
    userManualMiniGamesMemoryBody: 'اقلب البطاقات واعثر على الأزواج المتطابقة. تستخدم صور شخصيات Italian Brainrot. قريبا.',
    userManualMiniGamesReactionTitle: 'نقر رد الفعل',
    userManualMiniGamesReactionBody: 'اختبر سرعة رد فعلك. قريبا.',
    userManualMiniGamesOutro: 'عند انتهاء الاستراحة، تغلق صفحة الألعاب الصغيرة تلقائيا ويتم إعادتك إلى صفحة بومودورو لبدء جلسة التركيز التالية.',
    userManualProfileSubtitle: 'معلومات حسابك وإحصاءات الدراسة',
    userManualProfileBody: 'تعرض صفحة الملف الشخصي تفاصيل حسابك ونظرة عامة على إحصاءات نشاطك المتراكمة عبر جميع الجلسات.',
    userManualProfileFindTitle: 'ما ستجده',
    userManualProfileFindItem1: 'الاسم المعروض والبريد الإلكتروني ونوع الحساب (Google أو محلي)',
    userManualProfileFindItem2: 'إجمالي الملخصات التي تم إنشاؤها، والاختبارات التي تم إنشاؤها وحلها، والمقالات التي تم تقييمها، وجلسات المحادثة',
    userManualProfileFindItem3: 'سلسلة الأيام الحالية وأفضل سلسلة',
    userManualProfileFindItem4: 'خيار تغيير الاسم المعروض (للحسابات المحلية)',
    coursePreview: 'معاينة',
    courseDownload: 'تنزيل',
    coursePdfDocument: 'مستند PDF',
    coursePdfPreviewTitle: 'معاينة PDF',
    profileRankProgression: 'تقدم الرتب',
    profileRankLabel: 'الرتبة',
    profileRankCopper: 'نحاسي',
    profileRankBronze: 'برونزي',
    profileRankSilver: 'فضي',
    profileRankGold: 'ذهبي',
    profileRankPlatinum: 'بلاتيني',
    profileRankEmerald: 'زمردي',
    profileRankDiamond: 'ماسي',
    profileRankChampion: 'بطل',
    profileRankGrandChampion: 'بطل عظيم',
    profileRankLegend: 'أسطوري',
    profileLanguageEnglish: 'الإنجليزية',
    profileLanguageArabic: 'العربية',
  },
};

function getCopy(lang) {
  return COPY[lang] || COPY.en;
}

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('lang') || 'en');

  useEffect(() => {
    const nextLang = lang === 'ar' ? 'ar' : 'en';
    const nextDir = nextLang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.setAttribute('lang', nextLang);
    document.documentElement.setAttribute('dir', nextDir);
    localStorage.setItem('lang', nextLang);
  }, [lang]);

  const copy = useMemo(() => getCopy(lang), [lang]);
  const t = (key) => copy[key] ?? COPY.en[key] ?? key;
  const toggleLang = () => setLang((prev) => (prev === 'en' ? 'ar' : 'en'));

  return (
    <LanguageContext.Provider value={{ lang, setLang, toggleLang, t, copy }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
