import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const LanguageContext = createContext(null);

const COPY = {
  en: {
    greetingMorning: 'Good morning',
    greetingAfternoon: 'Good afternoon',
    greetingEvening: 'Good evening',
    greetingFallback: 'there',
    dateLocale: 'en-US',
    activeCourses: 'Active Courses',
    dayStreak: 'Day Streak',
    aiInteractions: 'AI Interactions',
    yourCourses: 'Your Courses',
    syncClassroom: 'Sync Classroom',
    syncing: 'Syncing...',
    noCoursesTitle: 'No courses found',
    noCoursesBody: 'Your dashboard is empty. Click "Sync Classroom" to fetch your official courses from Google.',
    quickActions: 'Quick Actions',
    askAi: 'Ask AI',
    askAiDesc: 'Instant help from your teaching assistant',
    summarize: 'Summarize',
    summarizeDesc: 'Condense lecture notes instantly',
    takeQuiz: 'Take a Quiz',
    takeQuizDesc: 'Test knowledge with AI quizzes',
    gradeEssay: 'Grade Essay',
    gradeEssayDesc: 'Predict your IELTS band score',
    lightMode: 'Light',
    darkMode: 'Dark',
    language: 'Language',
    navHome: 'Home',
    navCourses: 'Courses',
    navAiAgents: 'AI Agents',
    navFocusBreak: 'Focus & Break',
    navPomodoro: 'Pomodoro',
    navMiniGames: 'Mini Games',
    navSupport: 'Support',
    navUserManual: 'User Manual',
    navProfile: 'Profile',
    signOut: 'Sign out',
    availableDuringBreak: 'Available during break',
    backToAiAgents: 'Back to AI Agents',
    myCourses: 'My Courses',
    searchCourses: 'Search courses...',
    noCoursesMatch: 'No courses found matching your search.',
    noCourseSelected: 'No Course Selected',
    noCourseSelectedBody: 'Select a course from the sidebar to view its official documents, assignments, and lecture materials.',
    courseMaterials: 'Course Materials',
    files: 'Files',
    folderEmpty: 'Folder is Empty',
    folderEmptyBody: 'No documents have been synced from Google Classroom for this course yet.',
    coursesLoadError: 'Failed to load courses. Please try again.',
    downloadError: 'Failed to download document.',
    previewError: 'Failed to load document preview.',
    backToDashboard: 'Back to Dashboard',
    signInTagline: 'Your personalized AI-powered learning companion to enhance your educational journey.',
    signInButton: 'Continue with Google',
    aiAgentLabel: 'AI Agent',
    aiAgentsSubtitle: 'Choose an agent to get started',
    aiAgentsHint: 'Select an agent to begin • Hover to preview',
    aiSummarizerTitle: 'Summarizer',
    aiSummarizerContent: 'Turn long lecture notes into concise, exam-ready summaries.',
    aiQuizTitle: 'Quiz Generator',
    aiQuizContent: 'Generate practice quizzes from text or course documents.',
    aiChatTitle: 'AI Tutor Chat',
    aiChatContent: 'Ask follow-up questions and get concept explanations instantly.',
    aiEvaluatorTitle: 'Evaluator',
    aiEvaluatorContent: 'Evaluate summary quality and get structured feedback.',
    aiEssayTitle: 'Essay Grader',
    aiEssayContent: 'Predict IELTS band score and receive writing guidance.',
    profileKicker: 'Study Profile',
    profileTitleFallback: 'Student',
    profileSubtitle: 'Your learning hub and progress snapshot.',
    profileTotalInteractions: 'Total interactions',
    profileStreakBonus: 'Streak bonus',
    profileXp: 'Experience',
    profileLevel: 'Level',
    profileNextLevel: 'Next level at',
    profileRankFallback: 'Unranked',
    profileActiveCourses: 'Active Courses',
    profileStreak: 'Day Streak',
    profileFocusHours: 'Focus Hours',
    profileCompletedCycles: 'Focus Cycles',
    profileAchievements: 'Achievements',
    profileAchievementsHint: 'Progress updates daily',
    profileAchieved: 'Achieved',
    profileDailyTasks: 'Daily Tasks',
    profileTaskEmpty: 'No tasks yet. Complete a few actions to unlock today’s goals.',
    profileLoadingTasks: 'Updating tasks...',
    profileTaskCompleted: 'Completed',
    profileTaskReward: 'Reward',
    profileLearningProfile: 'Learning Profile',
    profileLoadingCourses: 'Loading courses...',
    profileNoCourses: 'No courses yet. Sync or create one to begin.',
    profileNextAction: 'Next action',
    profileOpenCourse: 'Open course',
    profileSettings: 'Account Settings',
    profileTheme: 'Theme',
    profileThemeDark: 'Dark',
    profileThemeLight: 'Light',
    profileLanguage: 'Language',
    profileNotifications: 'Notifications',
    automationTitle: 'Automation Preferences',
    automationBody: 'Choose the courses that should run automation.',
    automationAllCourses: 'All courses',
    automationEmpty: 'No courses available yet. Sync or create a course first.',
    automationSelectionHint: 'Select at least one course or choose "All courses".',
    automationSave: 'Save automation settings',
    automationSaved: 'Saved',
    automationModalTitle: 'Choose courses for automation',
    automationModalBody: 'Select which courses should be automated. You can change this later in Profile settings.',
    automationModalCta: 'Save and continue',
    profileAchievementStreak: '3-day streak',
    profileAchievementSummaries: '3 summaries created',
    profileAchievementQuizzes: '2 quizzes generated',
    profileAchievementFocus: '3 focus cycles',
    profileLeaderboard: 'Leaderboard',
    profileLeaderboardEmpty: 'No leaderboard data yet.',
    profileNextSummary: 'Create your first summary',
    profileNextQuiz: 'Generate a quiz',
    profileNextFocus: 'Start a focus session',
    profileNextReview: 'Review a recent result',
    timelineComplete: 'COMPLETE',
    timelineInProgress: 'IN PROGRESS',
    timelinePending: 'PENDING',
    timelineEnergy: 'Energy Level',
    timelineConnected: 'Connected Nodes',
    chatSeed: 'What are we learning today?',
    chatHeader: 'How can I assist you?',
    chatGeneral: 'General Chat',
    chatCourseContext: 'Course Context',
    chatSelectCourse: 'Select Course...',
    chatSelectDocument: 'Select Document...',
    chatAskPlaceholder: 'Ask a question...',
    chatError: '⚠️ Error connecting to chatbot. Please select a course if using Context Mode.',
    chatHistoryTab: 'History',
    chatHistoryTitle: 'Conversation History',
    chatHistoryNew: 'New chat',
    chatHistoryGeneralLabel: 'General',
    chatHistoryCourseLabel: 'Course',
    chatHistoryEmpty: 'No conversations yet.',
    chatHistorySelectCourse: 'Select a course to see history.',
    chatHistoryAuth: 'Log in to see your history.',
    chatHistoryLoading: 'Loading history...',
    chatHistoryLoadError: 'Unable to load history. Try again.',
    chatHistoryPreviewEmpty: 'No messages yet',
    chatTabChat: 'Chat',
    chatSpeak: 'Play answer audio',
    chatMicStart: 'Start recording',
    chatMicStop: 'Stop recording',
    chatMicUnsupported: 'Microphone access is not supported in this browser.',
    chatMicError: 'Microphone or transcription failed. Please try again.',
    chatMicEmpty: 'No speech detected. Try again.',
    chatTranscribing: 'Transcribing audio…',
    chatTtsError: 'Audio playback failed. Please try again.',
    quizTitle: 'AI Quiz Engine',
    quizSubtitle: 'Generate tests from your materials, or practice past quizzes.',
    quizTabGenerate: 'Generate Quiz',
    quizTabTake: 'Take a Quiz',
    quizSettings: 'Quiz Settings',
    quizSourceDocument: 'Document',
    quizSourceUpload: 'Upload',
    quizSourceText: 'Text',
    quizCourseLabel: 'Course Link',
    quizLoadingCourses: 'Loading courses…',
    quizSelectDocument: 'Select Document',
    quizLoading: 'Loading...',
    quizNoDocs: 'No docs found',
    quizChooseDocument: 'Choose a document...',
    quizUploadBrowse: 'Click to browse PDF',
    quizPasteTextLabel: 'Paste Text',
    quizPasteTextPlaceholder: 'Paste lecture notes here...',
    quizQuestionsLabel: 'Questions',
    quizOptionsLabel: 'Options',
    quizGenerating: 'Generating...',
    quizBuild: 'Build Quiz',
    quizSaved: 'Quiz saved! Find it in the "Take a Quiz" tab.',
    quizEphemeral: 'Ephemeral Quiz generated! (Not saved to database).',
    quizEmptyState: 'Configure settings and generate a quiz to start practicing.',
    quizYourQuizzes: 'Your Quizzes',
    quizLoadingQuizzes: 'Loading quizzes...',
    quizNoQuizzes: 'No quizzes for this course yet.',
    quizLabel: 'Quiz',
    quizTakeQuiz: 'Take Quiz',
    quizBackToQuizzes: 'Back to Quizzes',
    quizRevealAnswers: 'Reveal Answers',
    quizReset: 'Reset',
    quizScoreLabel: 'Score',
    quizAnswerLabel: 'Answer',
    quizDataNotFound: 'Data not found',
    quizGenerationFailed: 'Quiz generation failed.',
    summarizerTitle: 'AI Summarizer',
    summarizerSubtitle: 'Transform lengthy lecture materials or uploaded PDFs into concise notes.',
    summarizerConfig: 'Configuration',
    summarizerSourceDocument: 'Course Document',
    summarizerSourceUpload: 'Upload PDF',
    summarizerSelectCourse: 'Select Course',
    summarizerChooseCourse: 'Choose a course...',
    summarizerSelectDocument: 'Select Document',
    summarizerSelectCourseFirst: 'Select course first',
    summarizerNoDocs: 'No documents found',
    summarizerChooseDocument: 'Choose a document...',
    summarizerClickBrowse: 'Click to browse PDF',
    summarizerProcessedMemory: 'Processed in memory, never saved.',
    summarizerProcessing: 'Processing AI...',
    summarizerGenerate: 'Generate Summary',
    summarizerOutput: 'Summary Output',
    summarizerEmpty: 'Select a source and click generate to view the AI summary here.',
    summarizerError: 'Failed to generate summary. Please check your backend connection.',
    summarizerTabGenerate: 'Generate Summary',
    summarizerTabLibrary: 'My Summaries',
    summarizerLibraryTitle: 'Summary Library',
    summarizerLibrarySelectCourse: 'Filter by Course',
    summarizerLibraryAllCourses: 'All courses',
    summarizerLibraryLoading: 'Loading summaries...',
    summarizerLibraryEmpty: 'No summaries yet.',
    summarizerLibrarySelectHint: 'Select a summary to view it.',
    summarizerLibraryRefresh: 'Refresh',
    summarizerLibraryError: 'Failed to load summaries.',
    syncNewDocTitle: 'New document synced',
    syncSummaryQueuedTitle: 'Summary is getting ready',
    syncSummaryQueuedContent: 'Your summary is being prepared in the background.',
    syncSummaryReadyTitle: 'Summary is ready',
    syncSummaryReadyContent: 'Your summary is ready to open.',
    syncSummaryQueuedGeneric: 'We are preparing your new summaries.',
    syncQuizQueuedTitle: 'Quiz is getting ready',
    syncQuizQueuedContent: 'Your quiz is being prepared in the background.',
    syncQuizReadyTitle: 'Quiz is ready',
    syncQuizReadyContent: 'Your quiz is ready to take.',
    syncQuizQueuedGeneric: 'We are preparing your new quizzes.',
    docTypeAnnouncement: 'Announcement',
    docTypePost: 'Post',
    docTypeMaterial: 'Material',
    docTypeCoursework: 'Coursework',
    docTypeUpload: 'Uploaded File',
    docTypeDocument: 'Document',
    docNoContent: 'No content available.',
    evaluatorCourseLabel: 'Course',
    evaluatorLoadingCourses: 'Loading courses…',
    evaluatorLectureTitle: 'Lecture / Source Material',
    evaluatorInputType: 'Input type',
    evaluatorInputText: 'Enter Text',
    evaluatorInputDocument: 'Course Document',
    evaluatorLecturePlaceholder: 'Paste the original lecture notes or source material…',
    evaluatorChars: 'chars',
    evaluatorSelectDocument: 'Select document',
    evaluatorLoadingDocuments: 'Loading documents…',
    evaluatorNoUsableDocs: 'No usable documents found for this course. Sync Google Classroom materials first, or paste text manually.',
    evaluatorStudentSummaryTitle: 'Student Summary',
    evaluatorStudentSummaryPlaceholder: "Paste the student's summary to evaluate…",
    evaluatorSummaryInputType: 'Summary input type',
    evaluatorSummaryInputText: 'Enter Text',
    evaluatorSummaryInputUpload: 'Upload PDF',
    evaluatorSummaryUploadBrowse: 'Click to browse PDF',
    evaluatorSummaryUploadHint: 'Upload the student summary as a PDF file.',
    evaluatorStudentWordsUpload: 'PDF upload',
    evaluatorEvaluating: 'Evaluating…',
    evaluatorEvaluate: 'Evaluate Summary',
    evaluatorFailed: 'Evaluation failed.',
    evaluatorOverallScore: 'Overall Score',
    evaluatorStudentWords: 'Student words',
    evaluatorReferenceWords: 'Reference words',
    evaluatorKeyPoints: 'Key points',
    evaluatorMetrics: 'Metrics',
    evaluatorMetric: 'Metric',
    evaluatorScore: 'Score',
    evaluatorVisual: 'Visual',
    evaluatorDetails: 'Details / AI Feedback',
    evaluatorShowTechnical: 'Show technical details',
    evaluatorHideTechnical: 'Hide technical details',
    metricStrengthStrong: 'Strong.',
    metricStrengthOkay: 'Fair.',
    metricStrengthWeak: 'Needs work.',
    metricEvalError: 'We could not score this reliably. Try again or shorten the lecture.',
    metricCorrectness: 'Correctness',
    metricCorrectnessDesc: 'How close the summary is to the lecture and a reference summary.',
    metricRelevance: 'Relevance',
    metricRelevanceDesc: 'How well the summary focuses on the main lecture topics.',
    metricCoherence: 'Coherence',
    metricCoherenceDesc: 'How clear and well-organized the summary is.',
    metricCompleteness: 'Completeness',
    metricCompletenessDesc: 'How many important lecture points are included.',
    metricConciseness: 'Conciseness',
    metricConcisenessDesc: 'How close the length is to the reference summary.',
    metricTerminology: 'Terminology',
    metricTerminologyDesc: 'Use of important lecture terms.',
    metricHallucination: 'Hallucination',
    metricHallucinationDesc: 'Checks for claims not supported by the lecture.',
    metricMissingKeyPoints: 'Missing Key Points',
    metricMissingKeyPointsDesc: 'Important points from the lecture that were not mentioned.',
    metricFactualAccuracy: 'Factual Accuracy',
    metricFactualAccuracyDesc: 'Whether specific details and facts are correct.',
    metricCriticalAnalysis: 'Critical Analysis',
    metricCriticalAnalysisDesc: 'Depth of reasoning and connections between ideas.',
    essayPromptTitle: 'Essay Prompt (Optional)',
    essayPromptPlaceholder: 'Paste the essay question/prompt if your model was trained with question context...',
    essayInputType: 'Essay input type',
    essayInputText: 'Enter Text',
    essayInputUpload: 'Upload PDF',
    essayStudentEssay: 'Student Essay',
    essayTextPlaceholder: 'Paste the full essay text to predict IELTS band...',
    essayUploadBrowse: 'Click to browse PDF',
    essayUploadHint: 'Upload the student essay as a PDF file.',
    essayGrading: 'Grading...',
    essayPredict: 'Predict IELTS Band',
    essayEnterTextHint: 'Enter text in Student Essay to enable grading.',
    essayPredictedBand: 'Predicted IELTS Band',
    essayObjective: 'Objective',
    essayFailed: 'Essay grading failed.',
    pomodoroKicker: 'Productivity Focus',
    pomodoroBreak: 'Break Time',
    pomodoroFocus: 'Focus Session',
    pomodoroStart: 'Start',
    pomodoroPause: 'Pause',
    pomodoroReset: 'Reset',
    pomodoroSkipBreak: 'Skip Break',
    pomodoroModeWork: 'WORK',
    pomodoroModeBreak: 'BREAK',
    pomodoroAutoStart: 'Auto-start next session',
    pomodoroSessionSettings: 'Session Settings',
    pomodoroWorkSession: 'Work Session',
    pomodoroShortBreak: 'Short Break',
    pomodoroMinutes: 'minutes',
    pomodoroProgressBonus: 'Progress Bonus',
    pomodoroCompletedCycles: 'Completed Cycles',
    pomodoroStreakBonus: 'Streak Bonus',
    pomodoroNote: 'Every full focus cycle adds +10 streak points.',
    miniLockedTitle: 'Mini Games Locked',
    miniLockedBody: 'This tab is only available during Pomodoro breaks.',
    miniMemoryMatch: 'Memory Match',
    miniReset: 'Reset',
    miniMoves: 'Moves',
    miniCompleted: 'Completed!',
    miniPuzzle: '8-Puzzle',
    miniSolved: 'Solved!',
    miniPlay: 'Play',
    miniBackToGames: 'Back to Games',
    miniBreakMode: 'Break Mode Active',
    miniRelax: 'Relax with mini games',
    miniBreakEnds: 'Break ends in',
    miniUnavailable: 'Temporarily unavailable.',
    miniSlideTiles: 'Slide tiles into order from 1 to 8.',
    miniReactionClicker: 'Reaction Clicker',
    miniComingSoon: 'To be added soon',
    miniEmptyTile: 'Empty tile',
    miniTile: 'Tile',
    focusHubTitle: 'Focus Hub',
    tabFocusTimer: 'Focus Timer',
    tabMiniGames: 'Mini Games',
    dailyGoal: 'Daily Goal',
    todayFocus: 'Today',
    sessionTimeline: 'Session Timeline',
    focusGoalLabel: 'Goal',
    noSessionsYet: 'No sessions yet today',
    keyboardHintSpace: 'Space to start/pause',
    keyboardHintR: 'R to reset',
    gamesLockedHint: 'Complete a focus session to unlock games during your break',
    minutesShort: 'min',
    hoursShort: 'h',
    focusQuote1: 'The secret of getting ahead is getting started.',
    focusQuote2: 'Focus on being productive instead of busy.',
    focusQuote3: 'Small daily improvements lead to stunning results.',
    focusQuote4: 'Your focus determines your reality.',
    focusQuote5: 'Deep work is the superpower of the 21st century.',
    focusQuote6: 'Discipline is choosing what you want most over what you want now.',
    miniMemoryDesc: 'Match pairs of cards to test your memory.',
    miniMemoryCardAlt: 'Memory card',
    miniGamesPageTitle: 'Mini Games',
    miniGamesPageSubtitle: 'Take a brain break with fun mini games',
    miniBackToTimer: 'Back to Focus Timer',
    miniGoToGames: 'Play Mini Games',
    miniBreakCta: "You've earned a break! Relax with a quick game.",
    miniStartFocusFirst: 'Start a focus session to unlock games',
    reactionTitle: 'Reaction Clicker',
    reactionDesc: 'Test your reflexes! Click as fast as you can.',
    reactionWait: 'Wait for green...',
    reactionGo: 'CLICK NOW!',
    reactionTooEarly: 'Too early! Click to try again',
    reactionResult: 'Your reaction time',
    reactionMs: 'ms',
    reactionBest: 'Best',
    reactionAverage: 'Average',
    reactionRound: 'Round',
    reactionPlayAgain: 'Play Again',
    reactionRatingLightning: 'Lightning fast!',
    reactionRatingFast: 'Fast reflexes!',
    reactionRatingGood: 'Good reaction!',
    reactionRatingSlow: 'Keep practicing!',
    manualKicker: 'Platform Guide',
    manualTitle: 'MultiAgent AI Teaching Assistant User Manual',
    manualLead: 'This website is built to help students study faster and smarter by combining multiple AI tools in one workflow. Its main purpose is to support learning from classroom materials through summarization, quiz practice, tutoring conversations, and writing evaluation.',
    manualPurposeTitle: 'Primary Purpose Of The Website',
    manualPurposeList1: 'Centralize course content and AI learning tools in a single platform.',
    manualPurposeList2: 'Transform raw study material into summaries, quizzes, and guided explanations.',
    manualPurposeList3: 'Improve comprehension, retention, and writing performance with practical feedback loops.',
    manualPurposeList4: 'Reduce study time while increasing confidence before assessments.',
    manualUserManualTitle: 'User Manual (Current Tab)',
    manualUserManualHeading: 'User Manual',
    manualUserManualPurpose: 'This page is the central reference for using the platform and understanding how each feature fits your study workflow.',
    manualUserManualDescription: 'It explains the website purpose, the function of every left-side tab, and a recommended way to move from setup to revision. You can also share it with first-time users as a quick onboarding guide.',
    manualLeftTabsTitle: 'What Each Left-Side Tab Does',
    manualTabDashboard: 'Dashboard',
    manualTabDashboardPurpose: 'Your home overview after sign-in.',
    manualTabDashboardDetail1: 'Shows your greeting, date, and key study stats in one place.',
    manualTabDashboardDetail2: 'Lets you sync Google Classroom and refresh your enrolled course list.',
    manualTabDashboardDetail3: 'Provides quick action cards to open Chat, Summarizer, Quiz, and Essay Grader faster.',
    manualTabCourses: 'Courses',
    manualTabCoursesPurpose: 'Manage courses and their study materials.',
    manualTabCoursesDetail1: 'Open a course to view synced Google Classroom materials.',
    manualTabCoursesDetail2: 'Preview Drive documents in a new tab when needed.',
    manualTabPomodoro: 'Pomodoro',
    manualTabPomodoroPurpose: 'Run focused study sessions with timed breaks.',
    manualTabPomodoroDetail1: 'Default cycle is 30 minutes work + 5 minutes break, with editable durations.',
    manualTabPomodoroDetail2: 'Includes Start, Pause, Reset, Skip Break, and optional auto-start next session.',
    manualTabPomodoroDetail3: 'Tracks completed cycles and streak bonus points during your study routine.',
    manualTabMiniGames: 'Mini Games',
    manualTabMiniGamesPurpose: 'Take short break-time game sessions to refresh focus.',
    manualTabMiniGamesDetail1: 'Locked during work mode and unlocks only while Pomodoro break mode is active.',
    manualTabMiniGamesDetail2: 'Currently includes Memory Match with image cards and full-screen play mode.',
    manualTabMiniGamesDetail3: 'Returns you to study flow when break ends and game access is locked again.',
    manualTabSummarizer: 'Summarizer',
    manualTabSummarizerPurpose: 'Turn long content into concise study notes.',
    manualTabSummarizerDetail1: 'Paste text or select course documents to generate focused summaries.',
    manualTabSummarizerDetail2: 'Saves time before revision by extracting key concepts quickly.',
    manualTabSummarizerDetail3: 'Useful before exams to create rapid review material.',
    manualTabQuiz: 'Quiz Generator',
    manualTabQuizPurpose: 'Create and take AI-generated quizzes.',
    manualTabQuizDetail1: 'Generate quiz questions from custom text or course materials.',
    manualTabQuizDetail2: 'Adjust number of questions and options to match your level.',
    manualTabQuizDetail3: 'Switch to Take a Quiz mode to practice with saved quizzes by course.',
    manualTabChat: 'AI Tutor Chat',
    manualTabChatPurpose: 'Ask questions and get guided explanations.',
    manualTabChatDetail1: 'Use conversational learning to clarify topics step-by-step.',
    manualTabChatDetail2: 'Great for follow-up questions when lecture notes are confusing.',
    manualTabChatDetail3: 'Supports quick concept checks while you study.',
    manualTabEvaluator: 'Evaluator',
    manualTabEvaluatorPurpose: 'Evaluate summary quality and coverage.',
    manualTabEvaluatorDetail1: 'Compare generated summaries against expected quality dimensions.',
    manualTabEvaluatorDetail2: 'Highlights strengths and weak points to improve summary writing.',
    manualTabEvaluatorDetail3: 'Helps verify whether your notes preserved the essential meaning.',
    manualTabEssay: 'Essay Grader',
    manualTabEssayPurpose: 'Estimate essay quality using the grading model.',
    manualTabEssayDetail1: 'Submit essay text and receive an AI-based score with feedback cues.',
    manualTabEssayDetail2: 'Useful for iterative writing practice before final submissions.',
    manualTabEssayDetail3: 'Supports self-assessment and faster writing improvement cycles.',
  },
  ar: {
    greetingMorning: 'صباح الخير',
    greetingAfternoon: 'مساء الخير',
    greetingEvening: 'مساء النور',
    greetingFallback: 'هناك',
    dateLocale: 'ar-SA',
    activeCourses: 'الدورات النشطة',
    dayStreak: 'سلسلة الأيام',
    aiInteractions: 'تفاعلات الذكاء الاصطناعي',
    yourCourses: 'دوراتك',
    syncClassroom: 'مزامنة الصف',
    syncing: 'جارٍ المزامنة...',
    noCoursesTitle: 'لا توجد دورات',
    noCoursesBody: 'لوحة التحكم فارغة. اضغط "مزامنة الصف" لجلب الدورات من Google.',
    quickActions: 'إجراءات سريعة',
    askAi: 'اسأل الذكاء الاصطناعي',
    askAiDesc: 'مساعدة فورية من المساعد التعليمي',
    summarize: 'تلخيص',
    summarizeDesc: 'اختصار ملاحظات المحاضرة فورًا',
    takeQuiz: 'ابدأ اختبارًا',
    takeQuizDesc: 'اختبر معرفتك بأسئلة الذكاء الاصطناعي',
    gradeEssay: 'تقييم المقال',
    gradeEssayDesc: 'توقع درجة IELTS الخاصة بك',
    lightMode: 'فاتح',
    darkMode: 'داكن',
    language: 'اللغة',
    navHome: 'الرئيسية',
    navCourses: 'الدورات',
    navAiAgents: 'وكلاء الذكاء الاصطناعي',
    navFocusBreak: 'التركيز والاستراحة',
    navPomodoro: 'بومودورو',
    navMiniGames: 'ألعاب صغيرة',
    navSupport: 'الدعم',
    navUserManual: 'دليل المستخدم',
    signOut: 'تسجيل الخروج',
    availableDuringBreak: 'متاح أثناء الاستراحة',
    backToAiAgents: 'العودة لوكلاء الذكاء الاصطناعي',
    myCourses: 'دوراتي',
    searchCourses: 'ابحث عن الدورات...',
    noCoursesMatch: 'لا توجد دورات مطابقة لبحثك.',
    noCourseSelected: 'لم يتم اختيار دورة',
    noCourseSelectedBody: 'اختر دورة من القائمة الجانبية لعرض المواد والواجبات الرسمية.',
    courseMaterials: 'مواد الدورة',
    files: 'ملفات',
    folderEmpty: 'المجلد فارغ',
    folderEmptyBody: 'لم تتم مزامنة أي مستندات من Google Classroom لهذه الدورة بعد.',
    coursesLoadError: 'تعذر تحميل الدورات. يرجى المحاولة مرة أخرى.',
    downloadError: 'تعذر تنزيل المستند.',
    previewError: 'تعذر تحميل معاينة المستند.',
    backToDashboard: 'العودة إلى لوحة التحكم',
    signInTagline: 'رفيق تعلّم شخصي مدعوم بالذكاء الاصطناعي لتحسين رحلتك التعليمية.',
    signInButton: 'المتابعة باستخدام Google',
    aiAgentLabel: 'وكيل ذكاء اصطناعي',
    aiAgentsSubtitle: 'اختر وكيلاً للبدء',
    aiAgentsHint: 'اختر وكيلاً للبدء • مرّر للمعاينة',
    aiSummarizerTitle: 'الملخص',
    aiSummarizerContent: 'حوّل ملاحظات المحاضرة الطويلة إلى ملخصات قصيرة جاهزة للاختبار.',
    aiQuizTitle: 'مولد الاختبارات',
    aiQuizContent: 'أنشئ اختبارات تدريبية من النصوص أو وثائق المقرر.',
    aiChatTitle: 'محادثة المساعد الذكي',
    aiChatContent: 'اسأل أسئلة متابعة واحصل على شرح فوري للمفاهيم.',
    aiEvaluatorTitle: 'المقيّم',
    aiEvaluatorContent: 'قيّم جودة الملخص واحصل على ملاحظات منظمة.',
    aiEssayTitle: 'مصحح المقال',
    aiEssayContent: 'توقع درجة IELTS واحصل على إرشادات للكتابة.',
    navProfile: 'الملف الشخصي',
    profileKicker: 'ملف الدراسة',
    profileTitleFallback: 'طالب',
    profileSubtitle: 'مركز تعلمك وملخص التقدم.',
    profileTotalInteractions: 'إجمالي التفاعلات',
    profileStreakBonus: 'مكافأة السلسلة',
    profileAchieved: 'تم تحقيقه',
    profileAchievements: 'الإنجازات',
    profileAchievementsHint: 'تحديثات التقدم يومياً',
    profileAchievementStreak: 'سلسلة لمدة 3 أيام',
    profileAchievementSummaries: 'ملخصات مُنشأة',
    profileAchievementQuizzes: 'اختبارات مُنشأة',
    profileAchievementFocus: 'دورات تركيز',
    profileActiveCourses: 'الدورات النشطة',
    profileStreak: 'سلسلة الأيام',
    profileFocusHours: 'ساعات التركيز',
    profileCompletedCycles: 'الدورات المكتملة',
    profileLearningProfile: 'ملف التعلم',
    profileLoadingCourses: 'جارٍ تحميل المقررات...',
    profileNoCourses: 'لا توجد دورات بعد. قم بالمزامنة أو أنشئ دورة للبدء.',
    profileNextAction: 'الإجراء التالي',
    profileOpenCourse: 'افتح المقرر',
    profileSettings: 'إعدادات الحساب',
    profileTheme: 'السمة',
    profileThemeDark: 'داكن',
    profileThemeLight: 'فاتح',
    profileLanguage: 'اللغة',
    profileNotifications: 'الإشعارات',
    automationTitle: 'تفضيلات الأتمتة',
    automationBody: 'اختر المقررات التي تريد تشغيل الأتمتة عليها.',
    automationAllCourses: 'كل المقررات',
    automationEmpty: 'لا توجد مقررات بعد. قم بالمزامنة أو أنشئ مقررًا أولًا.',
    automationSelectionHint: 'اختر مقررًا واحدًا على الأقل أو حدّد "كل المقررات".',
    automationSave: 'حفظ إعدادات الأتمتة',
    automationSaved: 'تم الحفظ',
    automationModalTitle: 'اختر المقررات للأتمتة',
    automationModalBody: 'حدد المقررات التي تريد أتمتتها. يمكنك تعديل ذلك لاحقًا من إعدادات الملف الشخصي.',
    automationModalCta: 'حفظ والمتابعة',
    profileNextSummary: 'أنشئ أول ملخص',
    profileNextQuiz: 'انشئ اختبارًا',
    profileNextFocus: 'ابدأ جلسة تركيز',
    profileNextReview: 'مراجعة نتيجة حديثة',
    profileTaskReward: 'المكافأة',
    profileXp: 'الخبرة',
    profileLevel: 'المستوى',
    profileNextLevel: 'المستوى التالي عند',
    profileRankFallback: 'بدون رتبة',
    profileDailyTasks: 'مهام اليوم',
    profileTaskEmpty: 'لا توجد مهام بعد. أكمل بعض الإجراءات لفتح مهام اليوم.',
    profileLoadingTasks: 'جارٍ تحديث المهام...',
    profileTaskCompleted: 'مكتمل',
    profileTaskReward: 'المكافأة',
    profileLeaderboard: 'لوحة المتصدرين',
    profileLeaderboardEmpty: 'لا توجد بيانات ترتيب بعد.',
    timelineComplete: 'مكتمل',
    timelineInProgress: 'قيد التقدم',
    timelinePending: 'قيد الانتظار',
    timelineEnergy: 'مستوى الطاقة',
    timelineConnected: 'العُقد المرتبطة',
    chatSeed: 'ماذا نتعلم اليوم؟',
    chatHeader: 'كيف يمكنني مساعدتك؟',
    chatGeneral: 'محادثة عامة',
    chatCourseContext: 'سياق المقرر',
    chatSelectCourse: 'اختر مقرراً...',
    chatSelectDocument: 'اختر مستنداً...',
    chatAskPlaceholder: 'اطرح سؤالاً...',
    chatError: '⚠️ خطأ في الاتصال بالمحادث. يرجى اختيار مقرر إذا كنت تستخدم وضع السياق.',
    chatHistoryTab: 'السجل',
    chatHistoryTitle: 'سجل المحادثات',
    chatHistoryNew: 'محادثة جديدة',
    chatHistoryGeneralLabel: 'عام',
    chatHistoryCourseLabel: 'مقرر',
    chatHistoryEmpty: 'لا توجد محادثات بعد.',
    chatHistorySelectCourse: 'اختر مقرراً لعرض السجل.',
    chatHistoryAuth: 'سجّل الدخول لعرض السجل.',
    chatHistoryLoading: 'جارٍ تحميل السجل...',
    chatHistoryLoadError: 'تعذر تحميل السجل. حاول مرة أخرى.',
    chatHistoryPreviewEmpty: 'لا توجد رسائل بعد',
    chatTabChat: 'المحادثة',
    chatSpeak: 'تشغيل الإجابة صوتياً',
    chatMicStart: 'ابدأ التسجيل',
    chatMicStop: 'أوقف التسجيل',
    chatMicUnsupported: 'الوصول إلى الميكروفون غير مدعوم في هذا المتصفح.',
    chatMicError: 'فشل الميكروفون أو النسخ. الرجاء المحاولة مرة أخرى.',
    chatMicEmpty: 'لم يتم اكتشاف كلام. حاول مجدداً.',
    chatTranscribing: 'جارٍ نسخ الصوت…',
    chatTtsError: 'فشل تشغيل الصوت. حاول مرة أخرى.',
    quizTitle: 'محرك اختبارات الذكاء الاصطناعي',
    quizSubtitle: 'أنشئ اختبارات من موادك أو تدرب على اختبارات سابقة.',
    quizTabGenerate: 'إنشاء اختبار',
    quizTabTake: 'حل اختبار',
    quizSettings: 'إعدادات الاختبار',
    quizSourceDocument: 'مستند',
    quizSourceUpload: 'رفع ملف',
    quizSourceText: 'نص',
    quizCourseLabel: 'ربط المقرر',
    quizLoadingCourses: 'جارٍ تحميل المقررات…',
    quizSelectDocument: 'اختر مستنداً',
    quizLoading: 'جارٍ التحميل...',
    quizNoDocs: 'لا توجد مستندات',
    quizChooseDocument: 'اختر مستنداً...',
    quizUploadBrowse: 'اضغط لتصفح PDF',
    quizPasteTextLabel: 'ألصق النص',
    quizPasteTextPlaceholder: 'ألصق ملاحظات المحاضرة هنا...',
    quizQuestionsLabel: 'الأسئلة',
    quizOptionsLabel: 'الخيارات',
    quizGenerating: 'جارٍ الإنشاء...',
    quizBuild: 'إنشاء اختبار',
    quizSaved: 'تم حفظ الاختبار! ستجده في تبويب "حل اختبار".',
    quizEphemeral: 'تم إنشاء اختبار مؤقت! (غير محفوظ في قاعدة البيانات).',
    quizEmptyState: 'اضبط الإعدادات وأنشئ اختباراً لبدء التدريب.',
    quizYourQuizzes: 'اختباراتك',
    quizLoadingQuizzes: 'جارٍ تحميل الاختبارات...',
    quizNoQuizzes: 'لا توجد اختبارات لهذا المقرر بعد.',
    quizLabel: 'اختبار',
    quizTakeQuiz: 'ابدأ الاختبار',
    quizBackToQuizzes: 'العودة للاختبارات',
    quizRevealAnswers: 'إظهار الإجابات',
    quizReset: 'إعادة ضبط',
    quizScoreLabel: 'النتيجة',
    quizAnswerLabel: 'الإجابة',
    quizDataNotFound: 'لا توجد بيانات',
    quizGenerationFailed: 'فشل إنشاء الاختبار.',
    summarizerTitle: 'ملخص الذكاء الاصطناعي',
    summarizerSubtitle: 'حوّل مواد المحاضرة الطويلة أو ملفات PDF إلى ملاحظات موجزة.',
    summarizerConfig: 'الإعدادات',
    summarizerSourceDocument: 'مستند المقرر',
    summarizerSourceUpload: 'رفع PDF',
    summarizerSelectCourse: 'اختر المقرر',
    summarizerChooseCourse: 'اختر مقرراً...',
    summarizerSelectDocument: 'اختر المستند',
    summarizerSelectCourseFirst: 'اختر المقرر أولاً',
    summarizerNoDocs: 'لا توجد مستندات',
    summarizerChooseDocument: 'اختر مستنداً...',
    summarizerClickBrowse: 'اضغط لتصفح PDF',
    summarizerProcessedMemory: 'تتم المعالجة في الذاكرة دون حفظ.',
    summarizerProcessing: 'جارٍ المعالجة...',
    summarizerGenerate: 'إنشاء الملخص',
    summarizerOutput: 'مخرجات الملخص',
    summarizerEmpty: 'اختر المصدر واضغط إنشاء لعرض ملخص الذكاء الاصطناعي هنا.',
    summarizerError: 'تعذر إنشاء الملخص. يرجى التحقق من اتصال الخادم.',
    summarizerTabGenerate: 'إنشاء ملخص',
    summarizerTabLibrary: 'ملخصاتي',
    summarizerLibraryTitle: 'مكتبة الملخصات',
    summarizerLibrarySelectCourse: 'تصفية حسب المقرر',
    summarizerLibraryAllCourses: 'كل المقررات',
    summarizerLibraryLoading: 'جارٍ تحميل الملخصات...',
    summarizerLibraryEmpty: 'لا توجد ملخصات بعد.',
    summarizerLibrarySelectHint: 'اختر ملخصاً لعرضه.',
    summarizerLibraryRefresh: 'تحديث',
    summarizerLibraryError: 'تعذر تحميل الملخصات.',
    syncNewDocTitle: 'تمت مزامنة مستند جديد',
    syncSummaryQueuedTitle: 'جاري تحضير الملخص',
    syncSummaryQueuedContent: 'يتم تجهيز الملخص في الخلفية.',
    syncSummaryReadyTitle: 'الملخص جاهز',
    syncSummaryReadyContent: 'الملخص جاهز الآن للعرض.',
    syncSummaryQueuedGeneric: 'نقوم الآن بتحضير ملخصاتك الجديدة.',
    syncQuizQueuedTitle: 'جاري تحضير الاختبار',
    syncQuizQueuedContent: 'يتم تجهيز الاختبار في الخلفية.',
    syncQuizReadyTitle: 'الاختبار جاهز',
    syncQuizReadyContent: 'الاختبار جاهز الآن للحل.',
    syncQuizQueuedGeneric: 'نقوم الآن بتحضير اختباراتك الجديدة.',
    docTypeAnnouncement: 'إعلان',
    docTypePost: 'منشور',
    docTypeMaterial: 'مادة',
    docTypeCoursework: 'واجب',
    docTypeUpload: 'ملف مرفوع',
    docTypeDocument: 'مستند',
    docNoContent: 'لا يوجد محتوى متاح.',
    evaluatorCourseLabel: 'المقرر',
    evaluatorLoadingCourses: 'جارٍ تحميل المقررات…',
    evaluatorLectureTitle: 'المحاضرة / المادة المصدرية',
    evaluatorInputType: 'نوع الإدخال',
    evaluatorInputText: 'إدخال نص',
    evaluatorInputDocument: 'مستند المقرر',
    evaluatorLecturePlaceholder: 'ألصق ملاحظات المحاضرة أو المادة المصدرية…',
    evaluatorChars: 'حرف',
    evaluatorSelectDocument: 'اختر مستنداً',
    evaluatorLoadingDocuments: 'جارٍ تحميل المستندات…',
    evaluatorNoUsableDocs: 'لا توجد مستندات قابلة للاستخدام لهذا المقرر. قم بمزامنة مواد Google Classroom أولاً أو ألصق النص يدوياً.',
    evaluatorStudentSummaryTitle: 'ملخص الطالب',
    evaluatorStudentSummaryPlaceholder: 'ألصق ملخص الطالب للتقييم…',
    evaluatorSummaryInputType: 'نوع إدخال الملخص',
    evaluatorSummaryInputText: 'إدخال نص',
    evaluatorSummaryInputUpload: 'رفع PDF',
    evaluatorSummaryUploadBrowse: 'اضغط لتصفح PDF',
    evaluatorSummaryUploadHint: 'ارفع ملخص الطالب كملف PDF.',
    evaluatorStudentWordsUpload: 'رفع PDF',
    evaluatorEvaluating: 'جارٍ التقييم…',
    evaluatorEvaluate: 'تقييم الملخص',
    evaluatorFailed: 'فشل التقييم.',
    evaluatorOverallScore: 'النتيجة الإجمالية',
    evaluatorStudentWords: 'كلمات الطالب',
    evaluatorReferenceWords: 'كلمات المرجع',
    evaluatorKeyPoints: 'النقاط الرئيسية',
    evaluatorMetrics: 'المقاييس',
    evaluatorMetric: 'المقياس',
    evaluatorScore: 'النتيجة',
    evaluatorVisual: 'تمثيل',
    evaluatorDetails: 'التفاصيل / ملاحظات الذكاء الاصطناعي',
    metricCorrectness: 'الصحة',
    metricCorrectnessDesc: 'دمج: اتساق مع المحاضرة ومحاذاة المرجع وتطابق لغوي',
    metricRelevance: 'الملاءمة',
    metricRelevanceDesc: 'تغطية الموضوعات والأفكار الأساسية',
    metricCoherence: 'التماسك',
    metricCoherenceDesc: 'تدفق منطقي وقابلية قراءة الملخص',
    metricCompleteness: 'الاكتمال',
    metricCompletenessDesc: 'تغطية النقاط الرئيسية مع الاسترجاع مقابل المرجع',
    metricConciseness: 'الإيجاز',
    metricConcisenessDesc: 'كفاءة الطول مقارنة بالملخص المرجعي',
    metricTerminology: 'المصطلحات',
    metricTerminologyDesc: 'استخدام مفردات تخصصية للمحاضرة',
    metricHallucination: 'الهلوسة',
    metricHallucinationDesc: 'عقوبة على الادعاءات غير المدعومة في المحاضرة',
    metricMissingKeyPoints: 'نقاط رئيسية مفقودة',
    metricMissingKeyPointsDesc: 'تغطية النقاط الرئيسية المستخرجة',
    metricFactualAccuracy: 'الدقة الواقعية',
    metricFactualAccuracyDesc: 'صحة التفاصيل والادعاءات الواقعية',
    metricCriticalAnalysis: 'التحليل النقدي',
    metricCriticalAnalysisDesc: 'عمق الاستدلال والتحليل',
    essayPromptTitle: 'سؤال المقال (اختياري)',
    essayPromptPlaceholder: 'ألصق سؤال المقال إذا كان النموذج مدرباً على سياق السؤال...',
    essayInputType: 'نوع إدخال المقال',
    essayInputText: 'إدخال نص',
    essayInputUpload: 'رفع PDF',
    essayStudentEssay: 'مقال الطالب',
    essayTextPlaceholder: 'ألصق نص المقال الكامل لتوقع درجة IELTS...',
    essayUploadBrowse: 'اضغط لتصفح PDF',
    essayUploadHint: 'ارفع مقال الطالب كملف PDF.',
    essayGrading: 'جارٍ التصحيح...',
    essayPredict: 'توقع درجة IELTS',
    essayEnterTextHint: 'أدخل نص مقال الطالب لتمكين التصحيح.',
    essayPredictedBand: 'درجة IELTS المتوقعة',
    essayObjective: 'الهدف',
    essayFailed: 'فشل تصحيح المقال.',
    pomodoroKicker: 'تركيز الإنتاجية',
    pomodoroBreak: 'وقت الاستراحة',
    pomodoroFocus: 'جلسة تركيز',
    pomodoroStart: 'ابدأ',
    pomodoroPause: 'إيقاف مؤقت',
    pomodoroReset: 'إعادة ضبط',
    pomodoroSkipBreak: 'تخطي الاستراحة',
    pomodoroModeWork: 'عمل',
    pomodoroModeBreak: 'استراحة',
    pomodoroAutoStart: 'البدء التلقائي للجلسة التالية',
    pomodoroSessionSettings: 'إعدادات الجلسة',
    pomodoroWorkSession: 'جلسة عمل',
    pomodoroShortBreak: 'استراحة قصيرة',
    pomodoroMinutes: 'دقائق',
    pomodoroProgressBonus: 'مكافأة التقدم',
    pomodoroCompletedCycles: 'الدورات المكتملة',
    pomodoroStreakBonus: 'مكافأة السلسلة',
    pomodoroNote: 'كل دورة تركيز كاملة تضيف +10 نقاط للسلسلة.',
    miniLockedTitle: 'الألعاب الصغيرة مقفلة',
    miniLockedBody: 'هذا التبويب متاح فقط أثناء استراحات بومودورو.',
    miniMemoryMatch: 'مطابقة الذاكرة',
    miniReset: 'إعادة ضبط',
    miniMoves: 'الحركات',
    miniCompleted: 'اكتملت!',
    miniPuzzle: 'لغز 8',
    miniSolved: 'تم الحل!',
    miniPlay: 'ابدأ اللعب',
    miniBackToGames: 'العودة للألعاب',
    miniBreakMode: 'وضع الاستراحة نشط',
    miniRelax: 'استمتع بألعاب صغيرة',
    miniBreakEnds: 'تنتهي الاستراحة خلال',
    miniUnavailable: 'غير متاح مؤقتاً.',
    miniSlideTiles: 'حرّك البلاطات لترتيبها من 1 إلى 8.',
    miniReactionClicker: 'نقر رد الفعل',
    miniComingSoon: 'سيتم إضافته قريباً',
    miniEmptyTile: 'بلاطة فارغة',
    miniTile: 'بلاطة',
    focusHubTitle: 'مركز التركيز',
    tabFocusTimer: 'مؤقت التركيز',
    tabMiniGames: 'ألعاب صغيرة',
    dailyGoal: 'الهدف اليومي',
    todayFocus: 'اليوم',
    sessionTimeline: 'الجدول الزمني للجلسات',
    focusGoalLabel: 'الهدف',
    noSessionsYet: 'لا توجد جلسات اليوم بعد',
    keyboardHintSpace: 'مسافة للبدء/الإيقاف',
    keyboardHintR: 'R لإعادة الضبط',
    gamesLockedHint: 'أكمل جلسة تركيز لفتح الألعاب أثناء استراحتك',
    minutesShort: 'د',
    hoursShort: 'س',
    focusQuote1: 'سر التقدم هو البدء.',
    focusQuote2: 'ركّز على الإنتاجية بدلاً من الانشغال.',
    focusQuote3: 'تحسينات يومية صغيرة تقود لنتائج مذهلة.',
    focusQuote4: 'تركيزك يحدد واقعك.',
    focusQuote5: 'العمل العميق هو القوة الخارقة للقرن الحادي والعشرين.',
    focusQuote6: 'الانضباط هو اختيار ما تريده أكثر على ما تريده الآن.',
    miniMemoryDesc: 'طابق البطاقات لاختبار ذاكرتك.',
    miniMemoryCardAlt: 'بطاقة ذاكرة',
    miniGamesPageTitle: 'ألعاب صغيرة',
    miniGamesPageSubtitle: 'خذ استراحة ذهنية مع ألعاب ممتعة',
    miniBackToTimer: 'العودة لمؤقت التركيز',
    miniGoToGames: 'العب ألعاب صغيرة',
    miniBreakCta: 'لقد استحققت استراحة! استرخِ مع لعبة سريعة.',
    miniStartFocusFirst: 'ابدأ جلسة تركيز لفتح الألعاب',
    reactionTitle: 'نقر رد الفعل',
    reactionDesc: 'اختبر ردة فعلك! انقر بأسرع ما يمكنك.',
    reactionWait: 'انتظر اللون الأخضر...',
    reactionGo: 'انقر الآن!',
    reactionTooEarly: 'مبكر جداً! انقر للمحاولة مرة أخرى',
    reactionResult: 'وقت ردة فعلك',
    reactionMs: 'مللي ثانية',
    reactionBest: 'الأفضل',
    reactionAverage: 'المتوسط',
    reactionRound: 'الجولة',
    reactionPlayAgain: 'العب مرة أخرى',
    reactionRatingLightning: 'سريع كالبرق!',
    reactionRatingFast: 'ردة فعل سريعة!',
    reactionRatingGood: 'ردة فعل جيدة!',
    reactionRatingSlow: 'واصل التدريب!',
    manualKicker: 'دليل المنصة',
    manualTitle: 'دليل استخدام مساعد التدريس متعدد الوكلاء',
    manualLead: 'تم بناء هذا الموقع لمساعدة الطلاب على الدراسة بشكل أسرع وأذكى عبر دمج عدة أدوات ذكاء اصطناعي في سير عمل واحد. الهدف الرئيسي هو دعم التعلم من مواد الصف عبر التلخيص، وتدريب الاختبارات، والمحادثات التعليمية، وتقييم الكتابة.',
    manualPurposeTitle: 'الهدف الأساسي للموقع',
    manualPurposeList1: 'تجميع محتوى المقررات وأدوات التعلم الذكية في منصة واحدة.',
    manualPurposeList2: 'تحويل مواد الدراسة إلى ملخصات واختبارات وشروحات موجهة.',
    manualPurposeList3: 'تحسين الفهم والحفظ وأداء الكتابة عبر حلقات تغذية راجعة عملية.',
    manualPurposeList4: 'تقليل وقت الدراسة مع زيادة الثقة قبل التقييمات.',
    manualUserManualTitle: 'دليل المستخدم (التبويب الحالي)',
    manualUserManualHeading: 'دليل المستخدم',
    manualUserManualPurpose: 'هذه الصفحة هي المرجع الأساسي لاستخدام المنصة وفهم دور كل ميزة في سير الدراسة.',
    manualUserManualDescription: 'تشرح هدف الموقع ووظيفة كل تبويب جانبي وطريقة مقترحة للانتقال من الإعداد إلى المراجعة. يمكنك مشاركتها مع المستخدمين الجدد كدليل سريع.',
    manualLeftTabsTitle: 'ماذا يفعل كل تبويب جانبي',
    manualTabDashboard: 'لوحة التحكم',
    manualTabDashboardPurpose: 'نظرة عامة للصفحة الرئيسية بعد تسجيل الدخول.',
    manualTabDashboardDetail1: 'يعرض التحية والتاريخ وإحصاءات الدراسة الأساسية في مكان واحد.',
    manualTabDashboardDetail2: 'يسمح بمزامنة Google Classroom وتحديث قائمة المقررات المسجلة.',
    manualTabDashboardDetail3: 'يوفر بطاقات إجراءات سريعة لفتح المحادثة والملخص والاختبار ومصحح المقال بسرعة.',
    manualTabCourses: 'الدورات',
    manualTabCoursesPurpose: 'إدارة المقررات ومواد الدراسة.',
    manualTabCoursesDetail1: 'افتح مقررًا لعرض المواد التي تمت مزامنتها من Google Classroom.',
    manualTabCoursesDetail2: 'قم بمعاينة مستندات Drive في تبويب جديد عند الحاجة.',
    manualTabPomodoro: 'بومودورو',
    manualTabPomodoroPurpose: 'جلسات تركيز مع استراحات زمنية.',
    manualTabPomodoroDetail1: 'الدورة الافتراضية 30 دقيقة عمل + 5 دقائق استراحة مع إمكانية التعديل.',
    manualTabPomodoroDetail2: 'يتضمن بدء وإيقاف مؤقت وإعادة ضبط وتخطي الاستراحة والبدء التلقائي للجلسة التالية.',
    manualTabPomodoroDetail3: 'يتتبع الدورات المكتملة ونقاط السلسلة أثناء روتين الدراسة.',
    manualTabMiniGames: 'الألعاب الصغيرة',
    manualTabMiniGamesPurpose: 'جلسات لعب قصيرة لتجديد التركيز أثناء الاستراحة.',
    manualTabMiniGamesDetail1: 'مقفلة أثناء وضع العمل وتفتح فقط أثناء استراحة بومودورو.',
    manualTabMiniGamesDetail2: 'تتضمن حاليًا مطابقة الذاكرة مع وضع لعب بملء الشاشة.',
    manualTabMiniGamesDetail3: 'يعيدك إلى الدراسة عند انتهاء الاستراحة وإغلاق الوصول للألعاب.',
    manualTabSummarizer: 'الملخص',
    manualTabSummarizerPurpose: 'تحويل المحتوى الطويل إلى ملاحظات مختصرة.',
    manualTabSummarizerDetail1: 'ألصق النص أو اختر مستندات المقرر لإنشاء ملخصات مركزة.',
    manualTabSummarizerDetail2: 'يوفر الوقت قبل المراجعة باستخراج المفاهيم بسرعة.',
    manualTabSummarizerDetail3: 'مفيد قبل الاختبارات لإنشاء مواد مراجعة سريعة.',
    manualTabQuiz: 'مولد الاختبارات',
    manualTabQuizPurpose: 'إنشاء وحل اختبارات مولدة بالذكاء الاصطناعي.',
    manualTabQuizDetail1: 'إنشاء أسئلة اختبار من النصوص أو مواد المقرر.',
    manualTabQuizDetail2: 'تعديل عدد الأسئلة والخيارات بما يناسب المستوى.',
    manualTabQuizDetail3: 'التحويل إلى وضع حل الاختبار للتدرب على الاختبارات المحفوظة حسب المقرر.',
    manualTabChat: 'محادثة المساعد الذكي',
    manualTabChatPurpose: 'طرح الأسئلة والحصول على شروحات موجهة.',
    manualTabChatDetail1: 'استخدام التعلم الحواري لتوضيح الموضوعات خطوة بخطوة.',
    manualTabChatDetail2: 'مفيد لأسئلة المتابعة عندما تكون ملاحظات المحاضرة غير واضحة.',
    manualTabChatDetail3: 'يدعم التحقق السريع من المفاهيم أثناء الدراسة.',
    manualTabEvaluator: 'المقيّم',
    manualTabEvaluatorPurpose: 'تقييم جودة الملخص وتغطيته.',
    manualTabEvaluatorDetail1: 'مقارنة الملخصات بالمقاييس المتوقعة للجودة.',
    manualTabEvaluatorDetail2: 'يسلط الضوء على نقاط القوة والضعف لتحسين كتابة الملخص.',
    manualTabEvaluatorDetail3: 'يساعد على التحقق من حفظ المعنى الأساسي في الملاحظات.',
    manualTabEssay: 'مصحح المقال',
    manualTabEssayPurpose: 'تقدير جودة المقال باستخدام النموذج.',
    manualTabEssayDetail1: 'إرسال نص المقال والحصول على نتيجة مدعومة بالذكاء الاصطناعي.',
    manualTabEssayDetail2: 'مفيد للتدريب التكراري قبل التسليم النهائي.',
    manualTabEssayDetail3: 'يدعم التقييم الذاتي وتسريع تحسين الكتابة.',
  },
};

function getCopy(lang) {
  return COPY[lang] || COPY.en;
}

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('lang') || 'en');

  useEffect(() => {
    const nextLang = lang === 'ar' ? 'ar' : 'en';
    const nextDir = nextLang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.setAttribute('lang', nextLang);
    document.documentElement.setAttribute('dir', nextDir);
    localStorage.setItem('lang', nextLang);
  }, [lang]);

  const copy = useMemo(() => getCopy(lang), [lang]);
  const t = (key) => copy[key] ?? COPY.en[key] ?? key;
  const toggleLang = () => setLang((prev) => (prev === 'en' ? 'ar' : 'en'));

  return (
    <LanguageContext.Provider value={{ lang, setLang, toggleLang, t, copy }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
